// ============================================================
//  FOOTBALL DRAFT — PLAYER DATABASE v3
//  Extended attributes for deep tactical engine
//
//  NEW ATTRIBUTES:
//  height         — physical presence (40-100)
//  heading        — aerial threat / defensive heading
//  vision         — key pass range and quality
//  longPassing    — switches, diagonals
//  shortPassing   — tiki-taka ability
//  ballControl    — first touch under pressure
//  agility        — quick direction changes
//  balance        — hold ball while turning
//  reactions      — GK saves, striker snap shots
//  aggression     — duels, pressing intensity
//  interceptions  — reading passing lanes
//  marking        — man-marking ability
//  concentration  — late game errors
//  composure      — penalty box calmness
//  teamwork       — positional discipline, cover
//  offTheBall     — movement without ball
//  natFitness     — recovery between matches (stamina-related)
//  injuryProne    — affects consistency (inverse)
//  weakFoot       — left/right foot quality
//  freeKick       — dead ball delivery
//  longShots      — shots from distance
//  volleys        — technical shot quality
//  slidingTackle  — ground challenges
//  standingTackle — upright defensive challenges
//  jumping        — aerial contests
//  strength       — physical duels
//  acceleration   — burst speed
//  sprintSpeed    — max pace over distance
//
//  playerGroup: blocks all versions once one is drafted
// ============================================================

const PLAYERS = [

  // ══════════════════════════════════════════════════════════
  //  GOALKEEPERS
  // ══════════════════════════════════════════════════════════

  {
    name: "Thibaut Courtois — 18/19", playerGroup: "thibaut-courtois",
    nation: "Belgium", club: "Real Madrid", position: "GK", secondaryPositions: [],
    overall: 91, attack: 10, midfield: 15, defense: 91,
    pace: 42, physical: 82, technical: 60, intelligence: 88,
    workRate: 68, creativity: 20, finishing: 5, passing: 70,
    dribbling: 25, pressing: 15, aerial: 88, stamina: 72,
    defensiveAwareness: 90, tackling: 20, positioning: 91,
    transitionThreat: 8, pressResistance: 75, bigGameRating: 92,
    consistency: 88, leadership: 82, versatility: 20, weakFoot: 50,
    setPieces: 30, crossing: 10,
    goalkeeperRating: 91, reflexes: 92, commandOfArea: 88, distribution: 78,
    // Extended
    height: 96, heading: 72, vision: 60, longPassing: 62, shortPassing: 68,
    ballControl: 55, agility: 50, balance: 65, reactions: 93, aggression: 45,
    interceptions: 30, marking: 20, concentration: 88, composure: 88,
    teamwork: 72, offTheBall: 25, natFitness: 78, injuryProne: 18,
    freeKick: 15, longShots: 5, volleys: 5,
    slidingTackle: 15, standingTackle: 18, jumping: 88, strength: 82,
    acceleration: 38, sprintSpeed: 42,
    traits: ["shotStopper","bigGamePlayer","aerialCommander"],
    playstyles: ["lowBlock","organised"],
    positions: ["GK"], face: "faces/courtois.png", rarity: "special"
  },
  {
    name: "Thibaut Courtois — 14/15", playerGroup: "thibaut-courtois",
    nation: "Belgium", club: "Chelsea", position: "GK", secondaryPositions: [],
    overall: 87, attack: 8, midfield: 12, defense: 87,
    pace: 40, physical: 80, technical: 55, intelligence: 84,
    workRate: 65, creativity: 15, finishing: 5, passing: 65,
    dribbling: 20, pressing: 12, aerial: 84, stamina: 70,
    defensiveAwareness: 86, tackling: 18, positioning: 86,
    transitionThreat: 6, pressResistance: 70, bigGameRating: 84,
    consistency: 82, leadership: 74, versatility: 18, weakFoot: 48,
    setPieces: 25, crossing: 8,
    goalkeeperRating: 87, reflexes: 88, commandOfArea: 84, distribution: 72,
    height: 96, heading: 68, vision: 55, longPassing: 58, shortPassing: 62,
    ballControl: 50, agility: 46, balance: 60, reactions: 89, aggression: 42,
    interceptions: 26, marking: 18, concentration: 84, composure: 82,
    teamwork: 68, offTheBall: 22, natFitness: 74, injuryProne: 20,
    freeKick: 12, longShots: 5, volleys: 5,
    slidingTackle: 12, standingTackle: 15, jumping: 84, strength: 78,
    acceleration: 35, sprintSpeed: 38,
    traits: ["shotStopper","aerialCommander"],
    playstyles: ["lowBlock","organised"],
    positions: ["GK"], face: "faces/courtois.png", rarity: "gold"
  },
  {
    name: "Alisson Becker — 18/19", playerGroup: "alisson-becker",
    nation: "Brazil", club: "Liverpool", position: "GK", secondaryPositions: [],
    overall: 90, attack: 8, midfield: 12, defense: 90,
    pace: 40, physical: 80, technical: 65, intelligence: 90,
    workRate: 70, creativity: 18, finishing: 5, passing: 82,
    dribbling: 22, pressing: 12, aerial: 85, stamina: 70,
    defensiveAwareness: 89, tackling: 18, positioning: 90,
    transitionThreat: 10, pressResistance: 80, bigGameRating: 90,
    consistency: 89, leadership: 85, versatility: 20, weakFoot: 55,
    setPieces: 28, crossing: 8,
    goalkeeperRating: 90, reflexes: 89, commandOfArea: 87, distribution: 88,
    height: 91, heading: 72, vision: 70, longPassing: 72, shortPassing: 78,
    ballControl: 62, agility: 52, balance: 66, reactions: 90, aggression: 44,
    interceptions: 28, marking: 20, concentration: 90, composure: 90,
    teamwork: 76, offTheBall: 26, natFitness: 76, injuryProne: 15,
    freeKick: 14, longShots: 5, volleys: 5,
    slidingTackle: 14, standingTackle: 16, jumping: 86, strength: 78,
    acceleration: 36, sprintSpeed: 40,
    traits: ["sweepingKeeper","distributionExpert","calmUnderPressure"],
    playstyles: ["highPress","possession"],
    positions: ["GK"], face: "faces/alisson.png", rarity: "gold"
  },
  {
    name: "Manuel Neuer — 14/15", playerGroup: "manuel-neuer",
    nation: "Germany", club: "Bayern Munich", position: "GK", secondaryPositions: [],
    overall: 93, attack: 12, midfield: 16, defense: 93,
    pace: 55, physical: 84, technical: 74, intelligence: 94,
    workRate: 74, creativity: 22, finishing: 6, passing: 82,
    dribbling: 38, pressing: 20, aerial: 88, stamina: 74,
    defensiveAwareness: 92, tackling: 28, positioning: 92,
    transitionThreat: 18, pressResistance: 86, bigGameRating: 94,
    consistency: 92, leadership: 92, versatility: 38, weakFoot: 60,
    setPieces: 32, crossing: 12,
    goalkeeperRating: 93, reflexes: 91, commandOfArea: 96, distribution: 88,
    height: 93, heading: 78, vision: 72, longPassing: 76, shortPassing: 78,
    ballControl: 70, agility: 58, balance: 68, reactions: 92, aggression: 52,
    interceptions: 35, marking: 24, concentration: 92, composure: 90,
    teamwork: 82, offTheBall: 30, natFitness: 80, injuryProne: 14,
    freeKick: 20, longShots: 6, volleys: 6,
    slidingTackle: 22, standingTackle: 25, jumping: 90, strength: 84,
    acceleration: 44, sprintSpeed: 52,
    traits: ["sweepingKeeper","leader","aerialCommander","bigGamePlayer"],
    playstyles: ["highPress","organised"],
    positions: ["GK"], face: "faces/neuer.png", rarity: "special"
  },
  {
    name: "Ederson — 18/19", playerGroup: "ederson",
    nation: "Brazil", club: "Man City", position: "GK", secondaryPositions: [],
    overall: 88, attack: 11, midfield: 15, defense: 88,
    pace: 45, physical: 80, technical: 68, intelligence: 86,
    workRate: 68, creativity: 18, finishing: 5, passing: 86,
    dribbling: 30, pressing: 14, aerial: 82, stamina: 70,
    defensiveAwareness: 87, tackling: 22, positioning: 86,
    transitionThreat: 12, pressResistance: 84, bigGameRating: 85,
    consistency: 86, leadership: 80, versatility: 25, weakFoot: 60,
    setPieces: 25, crossing: 10,
    goalkeeperRating: 88, reflexes: 86, commandOfArea: 85, distribution: 92,
    height: 88, heading: 70, vision: 74, longPassing: 82, shortPassing: 80,
    ballControl: 66, agility: 50, balance: 64, reactions: 88, aggression: 42,
    interceptions: 28, marking: 20, concentration: 86, composure: 88,
    teamwork: 78, offTheBall: 24, natFitness: 76, injuryProne: 16,
    freeKick: 15, longShots: 5, volleys: 5,
    slidingTackle: 14, standingTackle: 18, jumping: 84, strength: 78,
    acceleration: 38, sprintSpeed: 44,
    traits: ["distributionExpert","sweepingKeeper","calmUnderPressure"],
    playstyles: ["possession","highPress"],
    positions: ["GK"], face: "faces/ederson.png", rarity: "gold"
  },
  {
    name: "Peter Schmeichel — 98/99", playerGroup: "peter-schmeichel",
    nation: "Denmark", club: "Man United", position: "GK", secondaryPositions: [],
    overall: 94, attack: 14, midfield: 10, defense: 94,
    pace: 44, physical: 88, technical: 68, intelligence: 90,
    workRate: 72, creativity: 14, finishing: 6, passing: 64,
    dribbling: 20, pressing: 16, aerial: 90, stamina: 74,
    defensiveAwareness: 92, tackling: 24, positioning: 90,
    transitionThreat: 10, pressResistance: 78, bigGameRating: 96,
    consistency: 88, leadership: 96, versatility: 18, weakFoot: 54,
    setPieces: 28, crossing: 10,
    goalkeeperRating: 94, reflexes: 92, commandOfArea: 96, distribution: 72,
    height: 93, heading: 82, vision: 62, longPassing: 64, shortPassing: 60,
    ballControl: 52, agility: 48, balance: 62, reactions: 94, aggression: 72,
    interceptions: 32, marking: 22, concentration: 90, composure: 86,
    teamwork: 78, offTheBall: 26, natFitness: 82, injuryProne: 12,
    freeKick: 18, longShots: 5, volleys: 5,
    slidingTackle: 18, standingTackle: 22, jumping: 92, strength: 88,
    acceleration: 36, sprintSpeed: 42,
    traits: ["aerialCommander","leader","bigGamePlayer","shotStopper"],
    playstyles: ["organised","direct"],
    positions: ["GK"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Gianluigi Buffon — 02/03", playerGroup: "buffon",
    nation: "Italy", club: "Juventus", position: "GK", secondaryPositions: [],
    overall: 95, attack: 9, midfield: 12, defense: 95,
    pace: 38, physical: 86, technical: 72, intelligence: 94,
    workRate: 70, creativity: 12, finishing: 5, passing: 66,
    dribbling: 18, pressing: 14, aerial: 88, stamina: 72,
    defensiveAwareness: 94, tackling: 22, positioning: 94,
    transitionThreat: 8, pressResistance: 82, bigGameRating: 96,
    consistency: 92, leadership: 94, versatility: 16, weakFoot: 54,
    setPieces: 26, crossing: 9,
    goalkeeperRating: 95, reflexes: 94, commandOfArea: 92, distribution: 70,
    height: 91, heading: 80, vision: 60, longPassing: 60, shortPassing: 62,
    ballControl: 58, agility: 52, balance: 68, reactions: 96, aggression: 58,
    interceptions: 30, marking: 22, concentration: 94, composure: 92,
    teamwork: 80, offTheBall: 24, natFitness: 80, injuryProne: 14,
    freeKick: 16, longShots: 5, volleys: 5,
    slidingTackle: 16, standingTackle: 20, jumping: 90, strength: 86,
    acceleration: 32, sprintSpeed: 36,
    traits: ["shotStopper","leader","bigGamePlayer","aerialCommander"],
    playstyles: ["organised","lowBlock"],
    positions: ["GK"], face: "faces/default.png", rarity: "special"
  },

  // ══════════════════════════════════════════════════════════
  //  RIGHT BACKS
  // ══════════════════════════════════════════════════════════

  {
    name: "Trent Alexander-Arnold — 21/22", playerGroup: "trent-alexander-arnold",
    nation: "England", club: "Liverpool", position: "RB", secondaryPositions: ["CM"],
    overall: 87, attack: 80, midfield: 78, defense: 72,
    pace: 78, physical: 70, technical: 86, intelligence: 84,
    workRate: 78, creativity: 88, finishing: 58, passing: 92,
    dribbling: 75, pressing: 65, aerial: 62, stamina: 78,
    defensiveAwareness: 68, tackling: 68, positioning: 76,
    transitionThreat: 78, pressResistance: 80, bigGameRating: 84,
    consistency: 80, leadership: 70, versatility: 82, weakFoot: 70,
    setPieces: 90, crossing: 94,
    height: 75, heading: 62, vision: 88, longPassing: 90, shortPassing: 86,
    ballControl: 82, agility: 74, balance: 76, reactions: 80, aggression: 58,
    interceptions: 64, marking: 65, concentration: 76, composure: 80,
    teamwork: 80, offTheBall: 78, natFitness: 80, injuryProne: 28,
    freeKick: 86, longShots: 62, volleys: 58,
    slidingTackle: 68, standingTackle: 70, jumping: 64, strength: 68,
    acceleration: 78, sprintSpeed: 76,
    traits: ["crossingSpecialist","setPieceExpert","attackingFullback","visionPasser"],
    playstyles: ["possession","wide","highPress"],
    positions: ["RB"], face: "faces/trent.png", rarity: "gold"
  },
  {
    name: "Achraf Hakimi — 21/22", playerGroup: "achraf-hakimi",
    nation: "Morocco", club: "PSG", position: "RB", secondaryPositions: ["RW"],
    overall: 86, attack: 82, midfield: 72, defense: 78,
    pace: 95, physical: 76, technical: 80, intelligence: 78,
    workRate: 85, creativity: 74, finishing: 65, passing: 78,
    dribbling: 84, pressing: 72, aerial: 65, stamina: 88,
    defensiveAwareness: 74, tackling: 76, positioning: 78,
    transitionThreat: 92, pressResistance: 74, bigGameRating: 82,
    consistency: 80, leadership: 68, versatility: 80, weakFoot: 72,
    setPieces: 62, crossing: 80,
    height: 78, heading: 64, vision: 74, longPassing: 72, shortPassing: 76,
    ballControl: 80, agility: 88, balance: 82, reactions: 82, aggression: 66,
    interceptions: 72, marking: 72, concentration: 76, composure: 76,
    teamwork: 78, offTheBall: 82, natFitness: 86, injuryProne: 20,
    freeKick: 58, longShots: 60, volleys: 58,
    slidingTackle: 76, standingTackle: 74, jumping: 68, strength: 74,
    acceleration: 96, sprintSpeed: 94,
    traits: ["paceAbuser","attackingFullback","overlappingRunner","transitionThreat"],
    playstyles: ["counterAttack","wide","direct"],
    positions: ["RB"], face: "faces/hakimi.png", rarity: "gold"
  },
  {
    name: "Dani Alves — 10/11", playerGroup: "dani-alves",
    nation: "Brazil", club: "Barcelona", position: "RB", secondaryPositions: ["RW"],
    overall: 90, attack: 84, midfield: 76, defense: 82,
    pace: 88, physical: 78, technical: 84, intelligence: 86,
    workRate: 92, creativity: 82, finishing: 66, passing: 84,
    dribbling: 86, pressing: 80, aerial: 68, stamina: 92,
    defensiveAwareness: 80, tackling: 80, positioning: 80,
    transitionThreat: 88, pressResistance: 80, bigGameRating: 90,
    consistency: 86, leadership: 80, versatility: 84, weakFoot: 76,
    setPieces: 70, crossing: 88,
    height: 72, heading: 64, vision: 82, longPassing: 80, shortPassing: 84,
    ballControl: 86, agility: 90, balance: 86, reactions: 84, aggression: 68,
    interceptions: 78, marking: 76, concentration: 82, composure: 82,
    teamwork: 88, offTheBall: 86, natFitness: 90, injuryProne: 16,
    freeKick: 66, longShots: 62, volleys: 62,
    slidingTackle: 80, standingTackle: 78, jumping: 70, strength: 76,
    acceleration: 88, sprintSpeed: 86,
    traits: ["attackingFullback","crossingSpecialist","overlappingRunner","highWorkRate","bigGamePlayer"],
    playstyles: ["possession","wide","highPress"],
    positions: ["RB"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Kyle Walker — 17/18", playerGroup: "kyle-walker",
    nation: "England", club: "Man City", position: "RB", secondaryPositions: [],
    overall: 84, attack: 70, midfield: 66, defense: 84,
    pace: 97, physical: 84, technical: 72, intelligence: 80,
    workRate: 86, creativity: 58, finishing: 46, passing: 72,
    dribbling: 70, pressing: 74, aerial: 72, stamina: 88,
    defensiveAwareness: 82, tackling: 80, positioning: 82,
    transitionThreat: 82, pressResistance: 74, bigGameRating: 80,
    consistency: 80, leadership: 70, versatility: 68, weakFoot: 64,
    setPieces: 44, crossing: 68,
    height: 80, heading: 68, vision: 66, longPassing: 64, shortPassing: 70,
    ballControl: 70, agility: 82, balance: 78, reactions: 80, aggression: 72,
    interceptions: 78, marking: 76, concentration: 78, composure: 74,
    teamwork: 82, offTheBall: 72, natFitness: 88, injuryProne: 22,
    freeKick: 40, longShots: 52, volleys: 46,
    slidingTackle: 80, standingTackle: 78, jumping: 72, strength: 82,
    acceleration: 98, sprintSpeed: 96,
    traits: ["elitePace","recoveryDefender","disciplinedDefender"],
    playstyles: ["highPress","counterAttack"],
    positions: ["RB"], face: "faces/walker.png", rarity: "gold"
  },
  {
    name: "Cafu — 01/02", playerGroup: "cafu",
    nation: "Brazil", club: "AS Roma", position: "RB", secondaryPositions: [],
    overall: 92, attack: 82, midfield: 72, defense: 86,
    pace: 90, physical: 84, technical: 80, intelligence: 86,
    workRate: 94, creativity: 72, finishing: 62, passing: 78,
    dribbling: 78, pressing: 80, aerial: 72, stamina: 96,
    defensiveAwareness: 86, tackling: 84, positioning: 86,
    transitionThreat: 86, pressResistance: 78, bigGameRating: 90,
    consistency: 90, leadership: 86, versatility: 76, weakFoot: 70,
    setPieces: 64, crossing: 84,
    height: 78, heading: 70, vision: 74, longPassing: 74, shortPassing: 78,
    ballControl: 80, agility: 84, balance: 80, reactions: 84, aggression: 70,
    interceptions: 84, marking: 82, concentration: 88, composure: 84,
    teamwork: 90, offTheBall: 84, natFitness: 94, injuryProne: 12,
    freeKick: 58, longShots: 58, volleys: 52,
    slidingTackle: 84, standingTackle: 84, jumping: 74, strength: 82,
    acceleration: 90, sprintSpeed: 88,
    traits: ["attackingFullback","overlappingRunner","highWorkRate","consistentPerformer"],
    playstyles: ["counterAttack","wide","direct"],
    positions: ["RB"], face: "faces/default.png", rarity: "special"
  },

  // ══════════════════════════════════════════════════════════
  //  LEFT BACKS
  // ══════════════════════════════════════════════════════════

  {
    name: "Alphonso Davies — 19/20", playerGroup: "alphonso-davies",
    nation: "Canada", club: "Bayern Munich", position: "LB", secondaryPositions: ["LW"],
    overall: 86, attack: 79, midfield: 72, defense: 78,
    pace: 97, physical: 74, technical: 78, intelligence: 76,
    workRate: 88, creativity: 72, finishing: 58, passing: 74,
    dribbling: 84, pressing: 78, aerial: 62, stamina: 90,
    defensiveAwareness: 72, tackling: 74, positioning: 74,
    transitionThreat: 94, pressResistance: 72, bigGameRating: 80,
    consistency: 78, leadership: 65, versatility: 80, weakFoot: 72,
    setPieces: 52, crossing: 76,
    height: 72, heading: 60, vision: 72, longPassing: 68, shortPassing: 74,
    ballControl: 82, agility: 92, balance: 86, reactions: 82, aggression: 64,
    interceptions: 68, marking: 68, concentration: 72, composure: 72,
    teamwork: 80, offTheBall: 84, natFitness: 88, injuryProne: 22,
    freeKick: 48, longShots: 56, volleys: 52,
    slidingTackle: 74, standingTackle: 72, jumping: 64, strength: 72,
    acceleration: 98, sprintSpeed: 96,
    traits: ["elitePace","attackingFullback","transitionThreat","overlappingRunner"],
    playstyles: ["highPress","counterAttack","wide"],
    positions: ["LB"], face: "faces/davies.png", rarity: "gold"
  },
  {
    name: "Andrew Robertson — 18/19", playerGroup: "andrew-robertson",
    nation: "Scotland", club: "Liverpool", position: "LB", secondaryPositions: [],
    overall: 87, attack: 74, midfield: 76, defense: 84,
    pace: 82, physical: 78, technical: 78, intelligence: 84,
    workRate: 96, creativity: 72, finishing: 52, passing: 82,
    dribbling: 74, pressing: 90, aerial: 70, stamina: 96,
    defensiveAwareness: 82, tackling: 82, positioning: 82,
    transitionThreat: 76, pressResistance: 78, bigGameRating: 84,
    consistency: 86, leadership: 82, versatility: 70, weakFoot: 70,
    setPieces: 58, crossing: 84,
    height: 74, heading: 66, vision: 74, longPassing: 76, shortPassing: 80,
    ballControl: 76, agility: 80, balance: 78, reactions: 80, aggression: 76,
    interceptions: 80, marking: 78, concentration: 84, composure: 78,
    teamwork: 90, offTheBall: 80, natFitness: 94, injuryProne: 18,
    freeKick: 54, longShots: 52, volleys: 50,
    slidingTackle: 82, standingTackle: 80, jumping: 68, strength: 76,
    acceleration: 82, sprintSpeed: 80,
    traits: ["highEnergyRunner","crossingSpecialist","pressMonster","consistentPerformer"],
    playstyles: ["highPress","wide"],
    positions: ["LB"], face: "faces/robertson.png", rarity: "gold"
  },
  {
    name: "Roberto Carlos — 01/02", playerGroup: "roberto-carlos",
    nation: "Brazil", club: "Real Madrid", position: "LB", secondaryPositions: ["LW"],
    overall: 93, attack: 86, midfield: 74, defense: 84,
    pace: 92, physical: 84, technical: 84, intelligence: 82,
    workRate: 90, creativity: 80, finishing: 70, passing: 80,
    dribbling: 82, pressing: 76, aerial: 68, stamina: 92,
    defensiveAwareness: 80, tackling: 82, positioning: 78,
    transitionThreat: 92, pressResistance: 78, bigGameRating: 92,
    consistency: 86, leadership: 82, versatility: 80, weakFoot: 80,
    setPieces: 88, crossing: 84,
    height: 68, heading: 62, vision: 78, longPassing: 78, shortPassing: 80,
    ballControl: 82, agility: 88, balance: 84, reactions: 84, aggression: 72,
    interceptions: 78, marking: 76, concentration: 82, composure: 82,
    teamwork: 86, offTheBall: 86, natFitness: 90, injuryProne: 16,
    freeKick: 96, longShots: 84, volleys: 72,
    slidingTackle: 82, standingTackle: 80, jumping: 66, strength: 82,
    acceleration: 94, sprintSpeed: 92,
    traits: ["attackingFullback","elitePace","setPieceExpert","crossingSpecialist","overlappingRunner"],
    playstyles: ["counterAttack","wide","direct"],
    positions: ["LB"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Theo Hernandez — 21/22", playerGroup: "theo-hernandez",
    nation: "France", club: "AC Milan", position: "LB", secondaryPositions: ["LW"],
    overall: 85, attack: 80, midfield: 70, defense: 78,
    pace: 90, physical: 82, technical: 76, intelligence: 74,
    workRate: 82, creativity: 72, finishing: 62, passing: 74,
    dribbling: 80, pressing: 70, aerial: 72, stamina: 84,
    defensiveAwareness: 72, tackling: 76, positioning: 74,
    transitionThreat: 88, pressResistance: 72, bigGameRating: 80,
    consistency: 78, leadership: 68, versatility: 78, weakFoot: 70,
    setPieces: 54, crossing: 78,
    height: 80, heading: 68, vision: 70, longPassing: 68, shortPassing: 72,
    ballControl: 78, agility: 84, balance: 80, reactions: 78, aggression: 68,
    interceptions: 70, marking: 70, concentration: 74, composure: 72,
    teamwork: 76, offTheBall: 80, natFitness: 84, injuryProne: 24,
    freeKick: 50, longShots: 60, volleys: 56,
    slidingTackle: 76, standingTackle: 74, jumping: 72, strength: 80,
    acceleration: 92, sprintSpeed: 90,
    traits: ["paceAbuser","attackingFullback","transitionThreat"],
    playstyles: ["counterAttack","direct","wide"],
    positions: ["LB"], face: "faces/theohernandez.png", rarity: "gold"
  },

  // ══════════════════════════════════════════════════════════
  //  CENTRE BACKS
  // ══════════════════════════════════════════════════════════

  {
    name: "Virgil van Dijk — 18/19", playerGroup: "virgil-van-dijk",
    nation: "Netherlands", club: "Liverpool", position: "CB", secondaryPositions: [],
    overall: 90, attack: 40, midfield: 52, defense: 90,
    pace: 76, physical: 90, technical: 72, intelligence: 90,
    workRate: 74, creativity: 44, finishing: 48, passing: 82,
    dribbling: 54, pressing: 68, aerial: 94, stamina: 78,
    defensiveAwareness: 90, tackling: 88, positioning: 90,
    transitionThreat: 38, pressResistance: 84, bigGameRating: 90,
    consistency: 88, leadership: 92, versatility: 44, weakFoot: 76,
    setPieces: 72, crossing: 44,
    height: 95, heading: 94, vision: 72, longPassing: 80, shortPassing: 78,
    ballControl: 72, agility: 70, balance: 80, reactions: 84, aggression: 74,
    interceptions: 86, marking: 88, concentration: 90, composure: 88,
    teamwork: 82, offTheBall: 58, natFitness: 82, injuryProne: 20,
    freeKick: 50, longShots: 46, volleys: 44,
    slidingTackle: 86, standingTackle: 90, jumping: 94, strength: 90,
    acceleration: 74, sprintSpeed: 76,
    traits: ["aerialDominator","leader","organiser","setPieceThreat"],
    playstyles: ["highPress","organised","possession"],
    positions: ["CB"], face: "faces/vandijk.png", rarity: "special"
  },
  {
    name: "Bobby Moore — 65/66", playerGroup: "bobby-moore",
    nation: "England", club: "West Ham", position: "CB", secondaryPositions: [],
    overall: 91, attack: 44, midfield: 58, defense: 91,
    pace: 66, physical: 78, technical: 80, intelligence: 98,
    workRate: 76, creativity: 54, finishing: 40, passing: 84,
    dribbling: 62, pressing: 70, aerial: 80, stamina: 80,
    defensiveAwareness: 98, tackling: 88, positioning: 96,
    transitionThreat: 30, pressResistance: 90, bigGameRating: 96,
    consistency: 90, leadership: 96, versatility: 52, weakFoot: 80,
    setPieces: 66, crossing: 46,
    height: 85, heading: 84, vision: 84, longPassing: 82, shortPassing: 84,
    ballControl: 80, agility: 68, balance: 80, reactions: 86, aggression: 62,
    interceptions: 96, marking: 94, concentration: 96, composure: 96,
    teamwork: 94, offTheBall: 60, natFitness: 84, injuryProne: 10,
    freeKick: 56, longShots: 42, volleys: 40,
    slidingTackle: 86, standingTackle: 90, jumping: 82, strength: 78,
    acceleration: 62, sprintSpeed: 64,
    traits: ["intelligentPositioner","leader","organiser","bigGamePlayer","consistentPerformer"],
    playstyles: ["organised","possession"],
    positions: ["CB"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Rúben Dias — 20/21", playerGroup: "ruben-dias",
    nation: "Portugal", club: "Man City", position: "CB", secondaryPositions: [],
    overall: 89, attack: 35, midfield: 50, defense: 89,
    pace: 74, physical: 86, technical: 74, intelligence: 92,
    workRate: 78, creativity: 40, finishing: 38, passing: 80,
    dribbling: 50, pressing: 70, aerial: 86, stamina: 78,
    defensiveAwareness: 92, tackling: 86, positioning: 90,
    transitionThreat: 30, pressResistance: 82, bigGameRating: 88,
    consistency: 90, leadership: 88, versatility: 42, weakFoot: 74,
    setPieces: 66, crossing: 38,
    height: 87, heading: 88, vision: 68, longPassing: 76, shortPassing: 78,
    ballControl: 72, agility: 68, balance: 78, reactions: 84, aggression: 72,
    interceptions: 88, marking: 88, concentration: 92, composure: 88,
    teamwork: 86, offTheBall: 50, natFitness: 82, injuryProne: 14,
    freeKick: 44, longShots: 40, volleys: 38,
    slidingTackle: 84, standingTackle: 88, jumping: 88, strength: 86,
    acceleration: 72, sprintSpeed: 72,
    traits: ["organisedDefender","leader","intelligentPositioner","consistentPerformer"],
    playstyles: ["organised","possession","highPress"],
    positions: ["CB"], face: "faces/rubendias.png", rarity: "gold"
  },
  {
    name: "William Saliba — 22/23", playerGroup: "william-saliba",
    nation: "France", club: "Arsenal", position: "CB", secondaryPositions: [],
    overall: 87, attack: 32, midfield: 46, defense: 87,
    pace: 82, physical: 84, technical: 72, intelligence: 84,
    workRate: 76, creativity: 36, finishing: 32, passing: 78,
    dribbling: 52, pressing: 68, aerial: 82, stamina: 78,
    defensiveAwareness: 86, tackling: 86, positioning: 86,
    transitionThreat: 34, pressResistance: 78, bigGameRating: 84,
    consistency: 84, leadership: 74, versatility: 42, weakFoot: 72,
    setPieces: 60, crossing: 34,
    height: 89, heading: 84, vision: 66, longPassing: 74, shortPassing: 76,
    ballControl: 70, agility: 74, balance: 76, reactions: 82, aggression: 68,
    interceptions: 84, marking: 84, concentration: 84, composure: 82,
    teamwork: 80, offTheBall: 46, natFitness: 80, injuryProne: 18,
    freeKick: 40, longShots: 36, volleys: 34,
    slidingTackle: 84, standingTackle: 86, jumping: 84, strength: 84,
    acceleration: 82, sprintSpeed: 82,
    traits: ["recoveryDefender","modernCentreback","aerialDominator"],
    playstyles: ["highPress","organised"],
    positions: ["CB"], face: "faces/saliba.png", rarity: "gold"
  },
  {
    name: "Antonio Rüdiger — 21/22", playerGroup: "antonio-rudiger",
    nation: "Germany", club: "Chelsea", position: "CB", secondaryPositions: [],
    overall: 87, attack: 38, midfield: 48, defense: 87,
    pace: 84, physical: 92, technical: 66, intelligence: 82,
    workRate: 80, creativity: 36, finishing: 40, passing: 72,
    dribbling: 50, pressing: 72, aerial: 86, stamina: 82,
    defensiveAwareness: 84, tackling: 88, positioning: 82,
    transitionThreat: 44, pressResistance: 76, bigGameRating: 86,
    consistency: 82, leadership: 80, versatility: 46, weakFoot: 70,
    setPieces: 58, crossing: 36,
    height: 91, heading: 88, vision: 60, longPassing: 66, shortPassing: 68,
    ballControl: 62, agility: 76, balance: 74, reactions: 80, aggression: 84,
    interceptions: 82, marking: 82, concentration: 80, composure: 76,
    teamwork: 78, offTheBall: 48, natFitness: 84, injuryProne: 20,
    freeKick: 42, longShots: 44, volleys: 42,
    slidingTackle: 86, standingTackle: 88, jumping: 88, strength: 92,
    acceleration: 84, sprintSpeed: 84,
    traits: ["physicalBeast","aerialDominator","aggressiveDefender","bigGamePlayer"],
    playstyles: ["highPress","direct"],
    positions: ["CB"], face: "faces/rudiger.png", rarity: "gold"
  },
  {
    name: "Fabio Cannavaro — 05/06", playerGroup: "fabio-cannavaro",
    nation: "Italy", club: "Juventus", position: "CB", secondaryPositions: [],
    overall: 93, attack: 36, midfield: 52, defense: 93,
    pace: 78, physical: 82, technical: 74, intelligence: 94,
    workRate: 80, creativity: 42, finishing: 38, passing: 76,
    dribbling: 56, pressing: 74, aerial: 84, stamina: 82,
    defensiveAwareness: 94, tackling: 90, positioning: 94,
    transitionThreat: 34, pressResistance: 86, bigGameRating: 94,
    consistency: 90, leadership: 92, versatility: 50, weakFoot: 76,
    setPieces: 62, crossing: 38,
    height: 72, heading: 82, vision: 72, longPassing: 72, shortPassing: 74,
    ballControl: 74, agility: 80, balance: 82, reactions: 88, aggression: 78,
    interceptions: 92, marking: 92, concentration: 94, composure: 90,
    teamwork: 88, offTheBall: 52, natFitness: 86, injuryProne: 14,
    freeKick: 44, longShots: 40, volleys: 38,
    slidingTackle: 88, standingTackle: 92, jumping: 78, strength: 80,
    acceleration: 76, sprintSpeed: 76,
    traits: ["intelligentPositioner","leader","consistentPerformer","aggressiveDefender"],
    playstyles: ["organised","lowBlock"],
    positions: ["CB"], face: "faces/default.png", rarity: "special"
    clutch:94,visionRange:78,offTheBall:44,aggression:86,adaptability:90,
  },
  {
    name: "Alessandro Bastoni — 22/23", playerGroup: "bastoni",
    nation: "Italy", club: "Inter Milan", position: "CB", secondaryPositions: ["LB"],
    overall: 86, attack: 42, midfield: 60, defense: 84,
    pace: 74, physical: 80, technical: 82, intelligence: 86,
    workRate: 76, creativity: 62, finishing: 38, passing: 84,
    dribbling: 66, pressing: 68, aerial: 78, stamina: 76,
    defensiveAwareness: 84, tackling: 80, positioning: 84,
    transitionThreat: 52, pressResistance: 84, bigGameRating: 82,
    consistency: 82, leadership: 74, versatility: 72, weakFoot: 78,
    setPieces: 58, crossing: 48,
    height: 88, heading: 80, vision: 80, longPassing: 82, shortPassing: 82,
    ballControl: 78, agility: 72, balance: 78, reactions: 80, aggression: 64,
    interceptions: 82, marking: 80, concentration: 82, composure: 84,
    teamwork: 82, offTheBall: 56, natFitness: 80, injuryProne: 18,
    freeKick: 46, longShots: 42, volleys: 40,
    slidingTackle: 78, standingTackle: 82, jumping: 80, strength: 80,
    acceleration: 72, sprintSpeed: 72,
    traits: ["ballPlayingDefender","modernCentreback","intelligentPositioner"],
    playstyles: ["possession","organised"],
    positions: ["CB"], face: "faces/bastoni.png", rarity: "gold"
  },

  // ══════════════════════════════════════════════════════════
  //  CDM
  // ══════════════════════════════════════════════════════════

  {
    name: "Rodri — 22/23", playerGroup: "rodri",
    nation: "Spain", club: "Man City", position: "CDM", secondaryPositions: ["CM"],
    overall: 91, attack: 62, midfield: 91, defense: 86,
    pace: 68, physical: 84, technical: 86, intelligence: 95,
    workRate: 88, creativity: 78, finishing: 60, passing: 90,
    dribbling: 72, pressing: 84, aerial: 80, stamina: 86,
    defensiveAwareness: 90, tackling: 86, positioning: 92,
    transitionThreat: 58, pressResistance: 92, bigGameRating: 90,
    consistency: 92, leadership: 86, versatility: 80, weakFoot: 80,
    setPieces: 70, crossing: 62,
    height: 85, heading: 80, vision: 86, longPassing: 88, shortPassing: 90,
    ballControl: 86, agility: 68, balance: 80, reactions: 86, aggression: 72,
    interceptions: 90, marking: 82, concentration: 92, composure: 92,
    teamwork: 92, offTheBall: 74, natFitness: 88, injuryProne: 14,
    freeKick: 66, longShots: 64, volleys: 58,
    slidingTackle: 84, standingTackle: 88, jumping: 82, strength: 84,
    acceleration: 62, sprintSpeed: 66,
    traits: ["midfielderColossus","calmUnderPressure","intelligentPositioner","consistentPerformer"],
    playstyles: ["possession","organised","highPress"],
    positions: ["CDM"], face: "faces/rodri.png", rarity: "special"
  },
  {
    name: "Lothar Matthäus — 91/92", playerGroup: "lothar-matthaus",
    nation: "Germany", club: "Inter Milan", position: "CDM", secondaryPositions: ["CM"],
    overall: 95, attack: 82, midfield: 95, defense: 88,
    pace: 80, physical: 90, technical: 90, intelligence: 96,
    workRate: 96, creativity: 86, finishing: 80, passing: 90,
    dribbling: 84, pressing: 90, aerial: 78, stamina: 96,
    defensiveAwareness: 92, tackling: 90, positioning: 92,
    transitionThreat: 78, pressResistance: 92, bigGameRating: 96,
    consistency: 92, leadership: 98, versatility: 92, weakFoot: 84,
    setPieces: 78, crossing: 74,
    height: 78, heading: 76, vision: 90, longPassing: 88, shortPassing: 90,
    ballControl: 90, agility: 80, balance: 84, reactions: 92, aggression: 88,
    interceptions: 92, marking: 86, concentration: 94, composure: 92,
    teamwork: 96, offTheBall: 86, natFitness: 96, injuryProne: 10,
    freeKick: 82, longShots: 88, volleys: 80,
    slidingTackle: 90, standingTackle: 90, jumping: 78, strength: 90,
    acceleration: 78, sprintSpeed: 78,
    traits: ["midfielderColossus","leader","bigGamePlayer","boxToBox","hardTackler","energeticRunner","intelligentPositioner"],
    playstyles: ["highPress","direct","organised","possession"],
    positions: ["CDM"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Claude Makélélé — 03/04", playerGroup: "claude-makelele",
    nation: "France", club: "Chelsea", position: "CDM", secondaryPositions: [],
    overall: 91, attack: 44, midfield: 86, defense: 90,
    pace: 70, physical: 80, technical: 78, intelligence: 94,
    workRate: 92, creativity: 56, finishing: 38, passing: 80,
    dribbling: 66, pressing: 86, aerial: 68, stamina: 90,
    defensiveAwareness: 96, tackling: 92, positioning: 96,
    transitionThreat: 40, pressResistance: 84, bigGameRating: 88,
    consistency: 90, leadership: 82, versatility: 62, weakFoot: 74,
    setPieces: 54, crossing: 44,
    height: 68, heading: 64, vision: 72, longPassing: 74, shortPassing: 80,
    ballControl: 78, agility: 76, balance: 82, reactions: 88, aggression: 78,
    interceptions: 96, marking: 88, concentration: 94, composure: 88,
    teamwork: 94, offTheBall: 70, natFitness: 92, injuryProne: 12,
    freeKick: 46, longShots: 42, volleys: 40,
    slidingTackle: 90, standingTackle: 90, jumping: 66, strength: 80,
    acceleration: 68, sprintSpeed: 68,
    traits: ["protectiveScreener","intelligentPositioner","pressMonster","hardTackler"],
    playstyles: ["organised","lowBlock"],
    positions: ["CDM"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Declan Rice — 23/24", playerGroup: "declan-rice",
    nation: "England", club: "Arsenal", position: "CDM", secondaryPositions: ["CM"],
    overall: 86, attack: 64, midfield: 85, defense: 82,
    pace: 72, physical: 84, technical: 78, intelligence: 84,
    workRate: 92, creativity: 66, finishing: 56, passing: 80,
    dribbling: 70, pressing: 88, aerial: 78, stamina: 90,
    defensiveAwareness: 84, tackling: 84, positioning: 84,
    transitionThreat: 62, pressResistance: 80, bigGameRating: 82,
    consistency: 84, leadership: 80, versatility: 74, weakFoot: 74,
    setPieces: 60, crossing: 58,
    height: 83, heading: 76, vision: 74, longPassing: 76, shortPassing: 80,
    ballControl: 78, agility: 72, balance: 78, reactions: 80, aggression: 76,
    interceptions: 84, marking: 80, concentration: 84, composure: 80,
    teamwork: 90, offTheBall: 72, natFitness: 90, injuryProne: 16,
    freeKick: 56, longShots: 62, volleys: 56,
    slidingTackle: 82, standingTackle: 84, jumping: 78, strength: 84,
    acceleration: 70, sprintSpeed: 72,
    traits: ["pressMonster","boxToBox","energeticRunner","disciplinedDefender"],
    playstyles: ["highPress","organised"],
    positions: ["CDM"], face: "faces/declanrice.png", rarity: "gold"
  },
  {
    name: "Sergio Busquets — 14/15", playerGroup: "sergio-busquets",
    nation: "Spain", club: "Barcelona", position: "CDM", secondaryPositions: ["CM"],
    overall: 92, attack: 56, midfield: 90, defense: 86,
    pace: 58, physical: 72, technical: 88, intelligence: 98,
    workRate: 82, creativity: 72, finishing: 44, passing: 90,
    dribbling: 76, pressing: 82, aerial: 68, stamina: 80,
    defensiveAwareness: 94, tackling: 82, positioning: 96,
    transitionThreat: 44, pressResistance: 96, bigGameRating: 90,
    consistency: 90, leadership: 86, versatility: 72, weakFoot: 84,
    setPieces: 66, crossing: 54,
    height: 79, heading: 64, vision: 90, longPassing: 86, shortPassing: 92,
    ballControl: 90, agility: 72, balance: 84, reactions: 84, aggression: 56,
    interceptions: 96, marking: 82, concentration: 96, composure: 96,
    teamwork: 96, offTheBall: 72, natFitness: 84, injuryProne: 14,
    freeKick: 58, longShots: 46, volleys: 44,
    slidingTackle: 76, standingTackle: 82, jumping: 68, strength: 72,
    acceleration: 54, sprintSpeed: 56,
    traits: ["intelligentPositioner","calmUnderPressure","metronomeMidfielder","pressResistant"],
    playstyles: ["possession","highPress","organised"],
    positions: ["CDM"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Casemiro — 19/20", playerGroup: "casemiro",
    nation: "Brazil", club: "Real Madrid", position: "CDM", secondaryPositions: [],
    overall: 88, attack: 58, midfield: 86, defense: 86,
    pace: 64, physical: 90, technical: 76, intelligence: 88,
    workRate: 88, creativity: 64, finishing: 60, passing: 78,
    dribbling: 66, pressing: 84, aerial: 86, stamina: 86,
    defensiveAwareness: 90, tackling: 92, positioning: 88,
    transitionThreat: 52, pressResistance: 84, bigGameRating: 88,
    consistency: 86, leadership: 84, versatility: 68, weakFoot: 76,
    setPieces: 64, crossing: 54,
    height: 83, heading: 84, vision: 72, longPassing: 72, shortPassing: 78,
    ballControl: 74, agility: 64, balance: 76, reactions: 84, aggression: 82,
    interceptions: 88, marking: 84, concentration: 88, composure: 82,
    teamwork: 86, offTheBall: 66, natFitness: 88, injuryProne: 16,
    freeKick: 58, longShots: 62, volleys: 56,
    slidingTackle: 88, standingTackle: 90, jumping: 86, strength: 90,
    acceleration: 58, sprintSpeed: 62,
    traits: ["hardTackler","aerialDominator","protectiveScreener","bigGamePlayer"],
    playstyles: ["organised","direct","highPress"],
    positions: ["CDM"], face: "faces/casemiro.png", rarity: "gold"
  },

  // ══════════════════════════════════════════════════════════
  //  CM
  // ══════════════════════════════════════════════════════════

  {
    name: "Jude Bellingham — 23/24", playerGroup: "jude-bellingham",
    nation: "England", club: "Real Madrid", position: "CM", secondaryPositions: ["CAM"],
    overall: 91, attack: 88, midfield: 89, defense: 70,
    pace: 80, physical: 84, technical: 88, intelligence: 90,
    workRate: 88, creativity: 86, finishing: 84, passing: 86,
    dribbling: 86, pressing: 80, aerial: 80, stamina: 88,
    defensiveAwareness: 68, tackling: 70, positioning: 88,
    transitionThreat: 84, pressResistance: 86, bigGameRating: 94,
    consistency: 88, leadership: 88, versatility: 86, weakFoot: 80,
    setPieces: 72, crossing: 72,
    height: 84, heading: 80, vision: 86, longPassing: 82, shortPassing: 86,
    ballControl: 88, agility: 80, balance: 84, reactions: 88, aggression: 76,
    interceptions: 68, marking: 64, concentration: 86, composure: 88,
    teamwork: 86, offTheBall: 88, natFitness: 90, injuryProne: 14,
    freeKick: 68, longShots: 80, volleys: 76,
    slidingTackle: 68, standingTackle: 72, jumping: 80, strength: 84,
    acceleration: 80, sprintSpeed: 80,
    traits: ["bigGamePlayer","boxToBox","goalScoringMidfielder","leader"],
    playstyles: ["direct","counterAttack","possession"],
    positions: ["CM"], face: "faces/bellingham.png", rarity: "special"
  },
  {
    name: "Kevin De Bruyne — 19/20", playerGroup: "kevin-de-bruyne",
    nation: "Belgium", club: "Man City", position: "CM", secondaryPositions: ["CAM"],
    overall: 91, attack: 86, midfield: 91, defense: 64,
    pace: 74, physical: 76, technical: 92, intelligence: 94,
    workRate: 80, creativity: 96, finishing: 80, passing: 96,
    dribbling: 84, pressing: 68, aerial: 68, stamina: 80,
    defensiveAwareness: 58, tackling: 58, positioning: 86,
    transitionThreat: 80, pressResistance: 86, bigGameRating: 90,
    consistency: 86, leadership: 82, versatility: 80, weakFoot: 82,
    setPieces: 88, crossing: 90,
    height: 81, heading: 66, vision: 96, longPassing: 96, shortPassing: 90,
    ballControl: 90, agility: 76, balance: 80, reactions: 86, aggression: 60,
    interceptions: 56, marking: 52, concentration: 84, composure: 88,
    teamwork: 84, offTheBall: 86, natFitness: 82, injuryProne: 30,
    freeKick: 86, longShots: 80, volleys: 76,
    slidingTackle: 54, standingTackle: 60, jumping: 68, strength: 74,
    acceleration: 74, sprintSpeed: 74,
    traits: ["visionPasser","chanceCreator","setPieceExpert","crossingSpecialist"],
    playstyles: ["possession","wide","counterAttack"],
    positions: ["CM"], face: "faces/debruyne.png", rarity: "special"
  },
  {
    name: "Luka Modric — 17/18", playerGroup: "luka-modric",
    nation: "Croatia", club: "Real Madrid", position: "CM", secondaryPositions: [],
    overall: 91, attack: 76, midfield: 92, defense: 74,
    pace: 70, physical: 68, technical: 94, intelligence: 96,
    workRate: 88, creativity: 90, finishing: 68, passing: 94,
    dribbling: 90, pressing: 80, aerial: 60, stamina: 86,
    defensiveAwareness: 72, tackling: 72, positioning: 86,
    transitionThreat: 70, pressResistance: 94, bigGameRating: 94,
    consistency: 88, leadership: 86, versatility: 78, weakFoot: 88,
    setPieces: 76, crossing: 70,
    height: 67, heading: 56, vision: 94, longPassing: 90, shortPassing: 94,
    ballControl: 96, agility: 90, balance: 92, reactions: 88, aggression: 62,
    interceptions: 70, marking: 66, concentration: 88, composure: 94,
    teamwork: 88, offTheBall: 86, natFitness: 86, injuryProne: 16,
    freeKick: 72, longShots: 72, volleys: 68,
    slidingTackle: 68, standingTackle: 72, jumping: 58, strength: 66,
    acceleration: 68, sprintSpeed: 68,
    traits: ["technicalMaestro","calmUnderPressure","bigGamePlayer","visionPasser"],
    playstyles: ["possession","organised"],
    positions: ["CM"], face: "faces/modric.png", rarity: "special"
  },
  {
    name: "Toni Kroos — 16/17", playerGroup: "toni-kroos",
    nation: "Germany", club: "Real Madrid", position: "CM", secondaryPositions: [],
    overall: 90, attack: 74, midfield: 92, defense: 72,
    pace: 60, physical: 70, technical: 94, intelligence: 97,
    workRate: 80, creativity: 88, finishing: 64, passing: 97,
    dribbling: 78, pressing: 66, aerial: 62, stamina: 78,
    defensiveAwareness: 70, tackling: 64, positioning: 84,
    transitionThreat: 62, pressResistance: 92, bigGameRating: 92,
    consistency: 90, leadership: 84, versatility: 72, weakFoot: 90,
    setPieces: 90, crossing: 84,
    height: 79, heading: 60, vision: 96, longPassing: 98, shortPassing: 94,
    ballControl: 92, agility: 72, balance: 86, reactions: 84, aggression: 54,
    interceptions: 68, marking: 60, concentration: 92, composure: 96,
    teamwork: 88, offTheBall: 82, natFitness: 80, injuryProne: 18,
    freeKick: 94, longShots: 78, volleys: 70,
    slidingTackle: 58, standingTackle: 64, jumping: 62, strength: 68,
    acceleration: 56, sprintSpeed: 58,
    traits: ["elitePasser","setPieceExpert","metronomeMidfielder","calmUnderPressure"],
    playstyles: ["possession","organised"],
    positions: ["CM"], face: "faces/kroos.png", rarity: "special"
  },
  {
    name: "Zinedine Zidane — 01/02", playerGroup: "zinedine-zidane",
    nation: "France", club: "Real Madrid", position: "CM", secondaryPositions: ["CAM"],
    overall: 96, attack: 88, midfield: 96, defense: 62,
    pace: 74, physical: 76, technical: 99, intelligence: 96,
    workRate: 78, creativity: 98, finishing: 82, passing: 94,
    dribbling: 96, pressing: 64, aerial: 70, stamina: 76,
    defensiveAwareness: 58, tackling: 56, positioning: 88,
    transitionThreat: 72, pressResistance: 96, bigGameRating: 98,
    consistency: 88, leadership: 88, versatility: 82, weakFoot: 90,
    setPieces: 82, crossing: 80,
    height: 85, heading: 72, vision: 98, longPassing: 94, shortPassing: 96,
    ballControl: 99, agility: 88, balance: 96, reactions: 90, aggression: 56,
    interceptions: 58, marking: 52, concentration: 88, composure: 96,
    teamwork: 86, offTheBall: 90, natFitness: 80, injuryProne: 22,
    freeKick: 88, longShots: 78, volleys: 90,
    slidingTackle: 50, standingTackle: 56, jumping: 70, strength: 74,
    acceleration: 72, sprintSpeed: 72,
    traits: ["technicalMaestro","visionPasser","dribbleMaestro","bigGamePlayer","calmUnderPressure"],
    playstyles: ["possession","direct","organised"],
    positions: ["CM"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Pedri — 21/22", playerGroup: "pedri",
    nation: "Spain", club: "Barcelona", position: "CM", secondaryPositions: ["CAM"],
    overall: 88, attack: 78, midfield: 88, defense: 62,
    pace: 72, physical: 62, technical: 92, intelligence: 90,
    workRate: 82, creativity: 88, finishing: 66, passing: 88,
    dribbling: 90, pressing: 78, aerial: 52, stamina: 80,
    defensiveAwareness: 60, tackling: 60, positioning: 82,
    transitionThreat: 68, pressResistance: 90, bigGameRating: 82,
    consistency: 82, leadership: 72, versatility: 76, weakFoot: 82,
    setPieces: 68, crossing: 64,
    height: 70, heading: 50, vision: 90, longPassing: 82, shortPassing: 92,
    ballControl: 94, agility: 90, balance: 92, reactions: 82, aggression: 52,
    interceptions: 60, marking: 56, concentration: 82, composure: 90,
    teamwork: 86, offTheBall: 84, natFitness: 82, injuryProne: 26,
    freeKick: 62, longShots: 62, volleys: 60,
    slidingTackle: 56, standingTackle: 62, jumping: 52, strength: 60,
    acceleration: 72, sprintSpeed: 70,
    traits: ["technicalMaestro","calmUnderPressure","dribbleMaestro","pressResistant"],
    playstyles: ["possession","highPress"],
    positions: ["CM"], face: "faces/pedri.png", rarity: "gold"
  },
  {
    name: "Martin Ødegaard — 23/24", playerGroup: "martin-odegaard",
    nation: "Norway", club: "Arsenal", position: "CM", secondaryPositions: ["CAM"],
    overall: 88, attack: 82, midfield: 88, defense: 60,
    pace: 74, physical: 66, technical: 90, intelligence: 88,
    workRate: 80, creativity: 90, finishing: 74, passing: 88,
    dribbling: 86, pressing: 74, aerial: 56, stamina: 78,
    defensiveAwareness: 58, tackling: 58, positioning: 82,
    transitionThreat: 72, pressResistance: 84, bigGameRating: 84,
    consistency: 84, leadership: 84, versatility: 78, weakFoot: 80,
    setPieces: 78, crossing: 70,
    height: 72, heading: 54, vision: 90, longPassing: 84, shortPassing: 88,
    ballControl: 90, agility: 82, balance: 84, reactions: 82, aggression: 58,
    interceptions: 58, marking: 54, concentration: 84, composure: 86,
    teamwork: 84, offTheBall: 84, natFitness: 80, injuryProne: 22,
    freeKick: 76, longShots: 72, volleys: 66,
    slidingTackle: 54, standingTackle: 60, jumping: 56, strength: 64,
    acceleration: 74, sprintSpeed: 72,
    traits: ["chanceCreator","technicalMaestro","leader","visionPasser"],
    playstyles: ["possession","highPress"],
    positions: ["CM"], face: "faces/odegaard.png", rarity: "gold"
  },

  // ══════════════════════════════════════════════════════════
  //  CAM
  // ══════════════════════════════════════════════════════════

  {
    name: "Diego Maradona — 86/87", playerGroup: "diego-maradona",
    nation: "Argentina", club: "Napoli", position: "CAM", secondaryPositions: ["LW","CM"],
    overall: 99, attack: 96, midfield: 96, defense: 52,
    pace: 82, physical: 72, technical: 99, intelligence: 96,
    workRate: 86, creativity: 99, finishing: 92, passing: 94,
    dribbling: 99, pressing: 70, aerial: 62, stamina: 82,
    defensiveAwareness: 48, tackling: 48, positioning: 94,
    transitionThreat: 90, pressResistance: 98, bigGameRating: 99,
    consistency: 90, leadership: 96, versatility: 90, weakFoot: 54,
    setPieces: 90, crossing: 82,
    height: 59, heading: 66, vision: 98, longPassing: 90, shortPassing: 96,
    ballControl: 99, agility: 98, balance: 99, reactions: 96, aggression: 72,
    interceptions: 50, marking: 44, concentration: 88, composure: 96,
    teamwork: 86, offTheBall: 96, natFitness: 84, injuryProne: 28,
    freeKick: 96, longShots: 86, volleys: 84,
    slidingTackle: 42, standingTackle: 48, jumping: 64, strength: 68,
    acceleration: 88, sprintSpeed: 82,
    traits: ["dribbleMaestro","creativeThreat","chanceCreator","bigGamePlayer","technicalMaestro","visionPasser","setPieceExpert"],
    playstyles: ["possession","direct","counterAttack"],
    positions: ["CAM"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Ronaldinho — 05/06", playerGroup: "ronaldinho",
    nation: "Brazil", club: "Barcelona", position: "CAM", secondaryPositions: ["LW"],
    overall: 97, attack: 94, midfield: 92, defense: 36,
    pace: 82, physical: 72, technical: 99, intelligence: 92,
    workRate: 68, creativity: 99, finishing: 88, passing: 90,
    dribbling: 99, pressing: 56, aerial: 68, stamina: 72,
    defensiveAwareness: 32, tackling: 30, positioning: 88,
    transitionThreat: 86, pressResistance: 92, bigGameRating: 96,
    consistency: 82, leadership: 74, versatility: 82, weakFoot: 92,
    setPieces: 84, crossing: 82,
    height: 73, heading: 66, vision: 96, longPassing: 88, shortPassing: 90,
    ballControl: 99, agility: 96, balance: 98, reactions: 90, aggression: 50,
    interceptions: 36, marking: 30, concentration: 78, composure: 92,
    teamwork: 74, offTheBall: 90, natFitness: 74, injuryProne: 22,
    freeKick: 90, longShots: 80, volleys: 82,
    slidingTackle: 30, standingTackle: 32, jumping: 64, strength: 68,
    acceleration: 86, sprintSpeed: 82,
    traits: ["dribbleMaestro","creativeThreat","chanceCreator","bigGamePlayer","technicalMaestro"],
    playstyles: ["possession","direct","wide"],
    positions: ["CAM"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Florian Wirtz — 23/24", playerGroup: "florian-wirtz",
    nation: "Germany", club: "Bayer Leverkusen", position: "CAM", secondaryPositions: ["RW"],
    overall: 89, attack: 88, midfield: 86, defense: 42,
    pace: 78, physical: 66, technical: 92, intelligence: 88,
    workRate: 76, creativity: 92, finishing: 82, passing: 86,
    dribbling: 90, pressing: 68, aerial: 54, stamina: 76,
    defensiveAwareness: 40, tackling: 40, positioning: 84,
    transitionThreat: 80, pressResistance: 86, bigGameRating: 86,
    consistency: 82, leadership: 68, versatility: 78, weakFoot: 82,
    setPieces: 72, crossing: 70,
    height: 74, heading: 52, vision: 90, longPassing: 80, shortPassing: 88,
    ballControl: 92, agility: 86, balance: 88, reactions: 86, aggression: 52,
    interceptions: 40, marking: 38, concentration: 80, composure: 86,
    teamwork: 76, offTheBall: 84, natFitness: 78, injuryProne: 20,
    freeKick: 68, longShots: 76, volleys: 72,
    slidingTackle: 36, standingTackle: 42, jumping: 52, strength: 62,
    acceleration: 80, sprintSpeed: 78,
    traits: ["chanceCreator","technicalMaestro","dribbleMaestro","creativeThreat"],
    playstyles: ["possession","direct","counterAttack"],
    positions: ["CAM"], face: "faces/wirtz.png", rarity: "special"
  },
  {
    name: "Phil Foden — 22/23", playerGroup: "phil-foden",
    nation: "England", club: "Man City", position: "CAM", secondaryPositions: ["LW","RW"],
    overall: 90, attack: 89, midfield: 84, defense: 44,
    pace: 80, physical: 68, technical: 92, intelligence: 88,
    workRate: 78, creativity: 90, finishing: 84, passing: 84,
    dribbling: 90, pressing: 72, aerial: 60, stamina: 78,
    defensiveAwareness: 42, tackling: 42, positioning: 86,
    transitionThreat: 80, pressResistance: 86, bigGameRating: 86,
    consistency: 84, leadership: 68, versatility: 82, weakFoot: 80,
    setPieces: 68, crossing: 72,
    height: 71, heading: 58, vision: 88, longPassing: 80, shortPassing: 86,
    ballControl: 92, agility: 86, balance: 88, reactions: 86, aggression: 54,
    interceptions: 42, marking: 40, concentration: 82, composure: 88,
    teamwork: 80, offTheBall: 86, natFitness: 80, injuryProne: 20,
    freeKick: 64, longShots: 76, volleys: 74,
    slidingTackle: 38, standingTackle: 44, jumping: 58, strength: 64,
    acceleration: 82, sprintSpeed: 80,
    traits: ["technicalMaestro","insideForward","dribbleMaestro","creativeThreat"],
    playstyles: ["possession","direct"],
    positions: ["CAM"], face: "faces/foden.png", rarity: "gold"
  },
  {
    name: "Bruno Fernandes — 21/22", playerGroup: "bruno-fernandes",
    nation: "Portugal", club: "Man United", position: "CAM", secondaryPositions: ["CM"],
    overall: 87, attack: 84, midfield: 86, defense: 58,
    pace: 72, physical: 70, technical: 86, intelligence: 84,
    workRate: 82, creativity: 88, finishing: 80, passing: 86,
    dribbling: 78, pressing: 72, aerial: 68, stamina: 80,
    defensiveAwareness: 54, tackling: 54, positioning: 82,
    transitionThreat: 74, pressResistance: 80, bigGameRating: 82,
    consistency: 74, leadership: 82, versatility: 76, weakFoot: 76,
    setPieces: 84, crossing: 72,
    height: 79, heading: 66, vision: 88, longPassing: 82, shortPassing: 86,
    ballControl: 86, agility: 74, balance: 78, reactions: 82, aggression: 62,
    interceptions: 54, marking: 50, concentration: 72, composure: 78,
    teamwork: 80, offTheBall: 82, natFitness: 82, injuryProne: 20,
    freeKick: 82, longShots: 74, volleys: 70,
    slidingTackle: 50, standingTackle: 56, jumping: 66, strength: 68,
    acceleration: 72, sprintSpeed: 72,
    traits: ["chanceCreator","setPieceExpert","goalScoringMidfielder","leader"],
    playstyles: ["direct","possession"],
    positions: ["CAM"], face: "faces/brunofernandes.png", rarity: "gold"
  },

  // ══════════════════════════════════════════════════════════
  //  LEFT WING
  // ══════════════════════════════════════════════════════════

  {
    name: "Kylian Mbappé — 21/22", playerGroup: "kylian-mbappe",
    nation: "France", club: "PSG", position: "LW", secondaryPositions: ["ST"],
    overall: 93, attack: 93, midfield: 76, defense: 36,
    pace: 97, physical: 78, technical: 88, intelligence: 86,
    workRate: 72, creativity: 84, finishing: 92, passing: 80,
    dribbling: 90, pressing: 64, aerial: 74, stamina: 82,
    defensiveAwareness: 34, tackling: 26, positioning: 92,
    transitionThreat: 97, pressResistance: 86, bigGameRating: 94,
    consistency: 88, leadership: 78, versatility: 80, weakFoot: 84,
    setPieces: 68, crossing: 76,
    height: 78, heading: 72, vision: 82, longPassing: 72, shortPassing: 80,
    ballControl: 90, agility: 92, balance: 88, reactions: 90, aggression: 58,
    interceptions: 34, marking: 28, concentration: 86, composure: 90,
    teamwork: 72, offTheBall: 92, natFitness: 84, injuryProne: 18,
    freeKick: 64, longShots: 80, volleys: 80,
    slidingTackle: 22, standingTackle: 28, jumping: 74, strength: 76,
    acceleration: 99, sprintSpeed: 97,
    traits: ["eliteFinisher","elitePace","transitionThreat","paceAbuser","bigGamePlayer","insideForward"],
    playstyles: ["counterAttack","direct","vertical"],
    positions: ["LW"], face: "faces/mbappe.png", rarity: "special"
  },
  {
    name: "Vinicius Jr — 22/23", playerGroup: "vinicius-jr",
    nation: "Brazil", club: "Real Madrid", position: "LW", secondaryPositions: [],
    overall: 92, attack: 92, midfield: 74, defense: 34,
    pace: 97, physical: 74, technical: 88, intelligence: 80,
    workRate: 72, creativity: 88, finishing: 84, passing: 74,
    dribbling: 96, pressing: 62, aerial: 64, stamina: 80,
    defensiveAwareness: 32, tackling: 28, positioning: 82,
    transitionThreat: 96, pressResistance: 80, bigGameRating: 90,
    consistency: 80, leadership: 66, versatility: 66, weakFoot: 74,
    setPieces: 54, crossing: 72,
    height: 76, heading: 62, vision: 80, longPassing: 66, shortPassing: 74,
    ballControl: 92, agility: 96, balance: 92, reactions: 88, aggression: 56,
    interceptions: 32, marking: 26, concentration: 76, composure: 80,
    teamwork: 68, offTheBall: 86, natFitness: 82, injuryProne: 22,
    freeKick: 50, longShots: 72, volleys: 70,
    slidingTackle: 24, standingTackle: 28, jumping: 62, strength: 70,
    acceleration: 98, sprintSpeed: 96,
    traits: ["elitePace","dribbleMaestro","insideForward","paceAbuser","transitionThreat"],
    playstyles: ["counterAttack","direct","wide"],
    positions: ["LW"], face: "faces/vinicius.png", rarity: "special"
  },
  {
    name: "Bukayo Saka — 23/24", playerGroup: "bukayo-saka",
    nation: "England", club: "Arsenal", position: "LW", secondaryPositions: ["RW"],
    overall: 89, attack: 89, midfield: 78, defense: 56,
    pace: 84, physical: 72, technical: 86, intelligence: 84,
    workRate: 88, creativity: 84, finishing: 78, passing: 82,
    dribbling: 88, pressing: 82, aerial: 64, stamina: 88,
    defensiveAwareness: 52, tackling: 54, positioning: 82,
    transitionThreat: 82, pressResistance: 82, bigGameRating: 86,
    consistency: 88, leadership: 74, versatility: 84, weakFoot: 80,
    setPieces: 70, crossing: 80,
    height: 75, heading: 62, vision: 82, longPassing: 76, shortPassing: 82,
    ballControl: 86, agility: 86, balance: 84, reactions: 84, aggression: 68,
    interceptions: 52, marking: 50, concentration: 86, composure: 84,
    teamwork: 86, offTheBall: 84, natFitness: 88, injuryProne: 16,
    freeKick: 66, longShots: 70, volleys: 66,
    slidingTackle: 50, standingTackle: 56, jumping: 62, strength: 68,
    acceleration: 86, sprintSpeed: 84,
    traits: ["consistentPerformer","dribbleMaestro","insideForward","highWorkRate"],
    playstyles: ["highPress","wide","possession"],
    positions: ["LW"], face: "faces/saka.png", rarity: "gold"
  },
  {
    name: "Ryan Giggs — 98/99", playerGroup: "ryan-giggs",
    nation: "Wales", club: "Man United", position: "LW", secondaryPositions: [],
    overall: 90, attack: 88, midfield: 76, defense: 42,
    pace: 92, physical: 72, technical: 88, intelligence: 82,
    workRate: 82, creativity: 88, finishing: 72, passing: 80,
    dribbling: 92, pressing: 66, aerial: 60, stamina: 84,
    defensiveAwareness: 40, tackling: 42, positioning: 78,
    transitionThreat: 90, pressResistance: 78, bigGameRating: 88,
    consistency: 84, leadership: 76, versatility: 72, weakFoot: 68,
    setPieces: 66, crossing: 80,
    height: 71, heading: 58, vision: 84, longPassing: 74, shortPassing: 80,
    ballControl: 90, agility: 92, balance: 90, reactions: 84, aggression: 60,
    interceptions: 42, marking: 38, concentration: 82, composure: 80,
    teamwork: 78, offTheBall: 86, natFitness: 86, injuryProne: 20,
    freeKick: 62, longShots: 68, volleys: 66,
    slidingTackle: 40, standingTackle: 44, jumping: 58, strength: 68,
    acceleration: 94, sprintSpeed: 92,
    traits: ["elitePace","dribbleMaestro","bigGamePlayer","consistentPerformer"],
    playstyles: ["direct","wide","counterAttack"],
    positions: ["LW"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Thierry Henry — 03/04 LW", playerGroup: "thierry-henry-lw",
    nation: "France", club: "Arsenal", position: "LW", secondaryPositions: ["ST"],
    overall: 94, attack: 94, midfield: 70, defense: 34,
    pace: 94, physical: 80, technical: 92, intelligence: 90,
    workRate: 78, creativity: 86, finishing: 92, passing: 80,
    dribbling: 90, pressing: 64, aerial: 72, stamina: 82,
    defensiveAwareness: 32, tackling: 28, positioning: 92,
    transitionThreat: 94, pressResistance: 84, bigGameRating: 92,
    consistency: 90, leadership: 80, versatility: 78, weakFoot: 78,
    setPieces: 72, crossing: 76,
    height: 82, heading: 70, vision: 84, longPassing: 74, shortPassing: 80,
    ballControl: 94, agility: 90, balance: 90, reactions: 90, aggression: 60,
    interceptions: 32, marking: 28, concentration: 88, composure: 90,
    teamwork: 76, offTheBall: 92, natFitness: 84, injuryProne: 16,
    freeKick: 68, longShots: 76, volleys: 76,
    slidingTackle: 24, standingTackle: 28, jumping: 72, strength: 78,
    acceleration: 96, sprintSpeed: 94,
    traits: ["eliteFinisher","paceAbuser","dribbleMaestro","insideForward","bigGamePlayer","transitionThreat"],
    playstyles: ["direct","counterAttack","wide"],
    positions: ["LW"], face: "faces/default.png", rarity: "special"
  },

  // ══════════════════════════════════════════════════════════
  //  RIGHT WING
  // ══════════════════════════════════════════════════════════

  {
    name: "Cristiano Ronaldo — 13/14", playerGroup: "cristiano-ronaldo",
    nation: "Portugal", club: "Real Madrid", position: "RW", secondaryPositions: ["LW","ST"],
    overall: 96, attack: 96, midfield: 74, defense: 36,
    pace: 90, physical: 84, technical: 90, intelligence: 88,
    workRate: 82, creativity: 84, finishing: 96, passing: 78,
    dribbling: 90, pressing: 64, aerial: 86, stamina: 88,
    defensiveAwareness: 34, tackling: 30, positioning: 94,
    transitionThreat: 90, pressResistance: 82, bigGameRating: 97,
    consistency: 90, leadership: 86, versatility: 80, weakFoot: 80,
    setPieces: 84, crossing: 72,
    height: 87, heading: 88, vision: 80, longPassing: 72, shortPassing: 78,
    ballControl: 90, agility: 86, balance: 86, reactions: 90, aggression: 66,
    interceptions: 34, marking: 30, concentration: 88, composure: 90,
    teamwork: 76, offTheBall: 94, natFitness: 92, injuryProne: 14,
    freeKick: 90, longShots: 86, volleys: 84,
    slidingTackle: 26, standingTackle: 32, jumping: 88, strength: 82,
    acceleration: 92, sprintSpeed: 90,
    traits: ["eliteFinisher","setPieceThreat","aerialThreat","bigGamePlayer","penaltyBoxPredator","paceAbuser"],
    playstyles: ["direct","wide","counterAttack"],
    positions: ["RW"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Mohamed Salah — 17/18", playerGroup: "mohamed-salah",
    nation: "Egypt", club: "Liverpool", position: "RW", secondaryPositions: ["ST"],
    overall: 92, attack: 92, midfield: 74, defense: 44,
    pace: 92, physical: 74, technical: 88, intelligence: 88,
    workRate: 84, creativity: 82, finishing: 92, passing: 78,
    dribbling: 90, pressing: 72, aerial: 62, stamina: 88,
    defensiveAwareness: 42, tackling: 40, positioning: 90,
    transitionThreat: 90, pressResistance: 84, bigGameRating: 90,
    consistency: 92, leadership: 72, versatility: 74, weakFoot: 80,
    setPieces: 66, crossing: 68,
    height: 75, heading: 60, vision: 80, longPassing: 70, shortPassing: 78,
    ballControl: 88, agility: 88, balance: 88, reactions: 88, aggression: 64,
    interceptions: 42, marking: 38, concentration: 90, composure: 88,
    teamwork: 80, offTheBall: 88, natFitness: 88, injuryProne: 16,
    freeKick: 62, longShots: 72, volleys: 70,
    slidingTackle: 36, standingTackle: 42, jumping: 60, strength: 70,
    acceleration: 94, sprintSpeed: 90,
    traits: ["eliteFinisher","insideForward","consistentPerformer","paceAbuser"],
    playstyles: ["counterAttack","direct","wide"],
    positions: ["RW"], face: "faces/salah.png", rarity: "special"
  },
  {
    name: "David Beckham — 98/99", playerGroup: "david-beckham",
    nation: "England", club: "Man United", position: "RW", secondaryPositions: ["CM"],
    overall: 88, attack: 80, midfield: 82, defense: 46,
    pace: 72, physical: 70, technical: 86, intelligence: 84,
    workRate: 86, creativity: 84, finishing: 70, passing: 90,
    dribbling: 74, pressing: 70, aerial: 62, stamina: 82,
    defensiveAwareness: 44, tackling: 50, positioning: 76,
    transitionThreat: 62, pressResistance: 78, bigGameRating: 90,
    consistency: 84, leadership: 80, versatility: 76, weakFoot: 64,
    setPieces: 98, crossing: 96,
    height: 73, heading: 60, vision: 90, longPassing: 94, shortPassing: 82,
    ballControl: 84, agility: 72, balance: 76, reactions: 80, aggression: 60,
    interceptions: 48, marking: 46, concentration: 84, composure: 84,
    teamwork: 84, offTheBall: 78, natFitness: 84, injuryProne: 18,
    freeKick: 98, longShots: 80, volleys: 68,
    slidingTackle: 48, standingTackle: 52, jumping: 60, strength: 66,
    acceleration: 70, sprintSpeed: 70,
    traits: ["crossingSpecialist","setPieceExpert","visionPasser","bigGamePlayer"],
    playstyles: ["wide","possession","direct"],
    positions: ["RW"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Rodrygo — 22/23", playerGroup: "rodrygo",
    nation: "Brazil", club: "Real Madrid", position: "RW", secondaryPositions: ["LW"],
    overall: 85, attack: 85, midfield: 72, defense: 36,
    pace: 86, physical: 66, technical: 84, intelligence: 80,
    workRate: 76, creativity: 80, finishing: 78, passing: 76,
    dribbling: 86, pressing: 64, aerial: 60, stamina: 78,
    defensiveAwareness: 34, tackling: 32, positioning: 78,
    transitionThreat: 82, pressResistance: 76, bigGameRating: 86,
    consistency: 78, leadership: 64, versatility: 74, weakFoot: 78,
    setPieces: 58, crossing: 68,
    height: 70, heading: 58, vision: 80, longPassing: 68, shortPassing: 76,
    ballControl: 84, agility: 88, balance: 84, reactions: 82, aggression: 52,
    interceptions: 34, marking: 30, concentration: 76, composure: 80,
    teamwork: 72, offTheBall: 82, natFitness: 80, injuryProne: 18,
    freeKick: 54, longShots: 66, volleys: 64,
    slidingTackle: 28, standingTackle: 34, jumping: 58, strength: 62,
    acceleration: 88, sprintSpeed: 86,
    traits: ["bigGamePlayer","dribbleMaestro","insideForward","clevreMovement"],
    playstyles: ["counterAttack","direct"],
    positions: ["RW"], face: "faces/rodrygo.png", rarity: "gold"
  },

  // ══════════════════════════════════════════════════════════
  //  STRIKERS
  // ══════════════════════════════════════════════════════════

  {
    name: "Erling Haaland — 22/23", playerGroup: "erling-haaland",
    nation: "Norway", club: "Man City", position: "ST", secondaryPositions: [],
    overall: 94, attack: 95, midfield: 58, defense: 22,
    pace: 88, physical: 92, technical: 76, intelligence: 82,
    workRate: 68, creativity: 62, finishing: 98, passing: 62,
    dribbling: 74, pressing: 58, aerial: 90, stamina: 82,
    defensiveAwareness: 22, tackling: 18, positioning: 96,
    transitionThreat: 90, pressResistance: 78, bigGameRating: 90,
    consistency: 86, leadership: 74, versatility: 42, weakFoot: 74,
    setPieces: 68, crossing: 42,
    height: 94, heading: 90, vision: 72, longPassing: 56, shortPassing: 62,
    ballControl: 78, agility: 78, balance: 78, reactions: 92, aggression: 72,
    interceptions: 22, marking: 18, concentration: 84, composure: 88,
    teamwork: 66, offTheBall: 94, natFitness: 84, injuryProne: 20,
    freeKick: 52, longShots: 68, volleys: 70,
    slidingTackle: 14, standingTackle: 18, jumping: 92, strength: 92,
    acceleration: 90, sprintSpeed: 88,
    traits: ["eliteFinisher","aerialDominator","penaltyBoxPredator","physicalBeast","paceAbuser"],
    playstyles: ["direct","counterAttack","vertical"],
    positions: ["ST"], face: "faces/haaland.png", rarity: "special"
  },
  {
    name: "Ronaldo R9 — 97/98", playerGroup: "ronaldo-r9",
    nation: "Brazil", club: "Inter Milan", position: "ST", secondaryPositions: [],
    overall: 97, attack: 97, midfield: 66, defense: 24,
    pace: 96, physical: 88, technical: 92, intelligence: 88,
    workRate: 72, creativity: 84, finishing: 98, passing: 72,
    dribbling: 94, pressing: 58, aerial: 78, stamina: 80,
    defensiveAwareness: 22, tackling: 20, positioning: 96,
    transitionThreat: 96, pressResistance: 82, bigGameRating: 98,
    consistency: 86, leadership: 78, versatility: 60, weakFoot: 84,
    setPieces: 70, crossing: 52,
    height: 82, heading: 78, vision: 82, longPassing: 64, shortPassing: 72,
    ballControl: 96, agility: 96, balance: 94, reactions: 96, aggression: 66,
    interceptions: 24, marking: 20, concentration: 86, composure: 94,
    teamwork: 70, offTheBall: 94, natFitness: 82, injuryProne: 26,
    freeKick: 66, longShots: 80, volleys: 82,
    slidingTackle: 16, standingTackle: 20, jumping: 80, strength: 86,
    acceleration: 98, sprintSpeed: 96,
    traits: ["eliteFinisher","paceAbuser","dribbleMaestro","penaltyBoxPredator","bigGamePlayer","physicalBeast"],
    playstyles: ["direct","counterAttack","vertical"],
    positions: ["ST"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Harry Kane — 23/24", playerGroup: "harry-kane",
    nation: "England", club: "Bayern Munich", position: "ST", secondaryPositions: [],
    overall: 91, attack: 92, midfield: 72, defense: 28,
    pace: 70, physical: 82, technical: 84, intelligence: 92,
    workRate: 80, creativity: 78, finishing: 92, passing: 84,
    dribbling: 72, pressing: 68, aerial: 88, stamina: 80,
    defensiveAwareness: 26, tackling: 24, positioning: 94,
    transitionThreat: 68, pressResistance: 84, bigGameRating: 90,
    consistency: 88, leadership: 86, versatility: 68, weakFoot: 84,
    setPieces: 82, crossing: 54,
    height: 88, heading: 88, vision: 82, longPassing: 78, shortPassing: 82,
    ballControl: 84, agility: 70, balance: 78, reactions: 88, aggression: 68,
    interceptions: 26, marking: 24, concentration: 90, composure: 90,
    teamwork: 82, offTheBall: 92, natFitness: 82, injuryProne: 18,
    freeKick: 78, longShots: 74, volleys: 74,
    slidingTackle: 20, standingTackle: 24, jumping: 90, strength: 82,
    acceleration: 68, sprintSpeed: 68,
    traits: ["eliteFinisher","setPieceThreat","linkUpPlay","intelligentMover","leader"],
    playstyles: ["possession","direct","wide"],
    positions: ["ST"], face: "faces/kane.png", rarity: "gold"
  },
  {
    name: "Robert Lewandowski — 20/21", playerGroup: "robert-lewandowski",
    nation: "Poland", club: "Bayern Munich", position: "ST", secondaryPositions: [],
    overall: 93, attack: 93, midfield: 70, defense: 26,
    pace: 76, physical: 84, technical: 86, intelligence: 92,
    workRate: 78, creativity: 74, finishing: 97, passing: 78,
    dribbling: 76, pressing: 68, aerial: 86, stamina: 80,
    defensiveAwareness: 24, tackling: 22, positioning: 98,
    transitionThreat: 68, pressResistance: 84, bigGameRating: 90,
    consistency: 92, leadership: 82, versatility: 64, weakFoot: 84,
    setPieces: 76, crossing: 46,
    height: 85, heading: 86, vision: 78, longPassing: 72, shortPassing: 78,
    ballControl: 86, agility: 76, balance: 80, reactions: 90, aggression: 68,
    interceptions: 24, marking: 22, concentration: 92, composure: 90,
    teamwork: 78, offTheBall: 94, natFitness: 82, injuryProne: 14,
    freeKick: 72, longShots: 72, volleys: 76,
    slidingTackle: 18, standingTackle: 22, jumping: 88, strength: 84,
    acceleration: 74, sprintSpeed: 74,
    traits: ["eliteFinisher","penaltyBoxPredator","intelligentMover","setPieceThreat","consistentPerformer"],
    playstyles: ["possession","direct"],
    positions: ["ST"], face: "faces/lewandowski.png", rarity: "special"
  },
  {
    name: "Thierry Henry — 03/04", playerGroup: "thierry-henry",
    nation: "France", club: "Arsenal", position: "ST", secondaryPositions: ["LW"],
    overall: 96, attack: 96, midfield: 72, defense: 34,
    pace: 94, physical: 80, technical: 92, intelligence: 90,
    workRate: 78, creativity: 86, finishing: 94, passing: 80,
    dribbling: 90, pressing: 64, aerial: 72, stamina: 82,
    defensiveAwareness: 32, tackling: 28, positioning: 94,
    transitionThreat: 94, pressResistance: 84, bigGameRating: 92,
    consistency: 90, leadership: 80, versatility: 78, weakFoot: 78,
    setPieces: 72, crossing: 76,
    height: 82, heading: 70, vision: 84, longPassing: 74, shortPassing: 80,
    ballControl: 94, agility: 90, balance: 90, reactions: 90, aggression: 60,
    interceptions: 32, marking: 28, concentration: 88, composure: 90,
    teamwork: 76, offTheBall: 94, natFitness: 84, injuryProne: 16,
    freeKick: 68, longShots: 76, volleys: 76,
    slidingTackle: 24, standingTackle: 28, jumping: 72, strength: 78,
    acceleration: 96, sprintSpeed: 94,
    traits: ["eliteFinisher","paceAbuser","dribbleMaestro","insideForward","bigGamePlayer","transitionThreat"],
    playstyles: ["direct","counterAttack","wide"],
    positions: ["ST"], face: "faces/default.png", rarity: "special"
  },
  {
    name: "Victor Osimhen — 22/23", playerGroup: "victor-osimhen",
    nation: "Nigeria", club: "Napoli", position: "ST", secondaryPositions: [],
    overall: 89, attack: 90, midfield: 60, defense: 24,
    pace: 92, physical: 88, technical: 74, intelligence: 76,
    workRate: 72, creativity: 62, finishing: 88, passing: 60,
    dribbling: 74, pressing: 64, aerial: 82, stamina: 80,
    defensiveAwareness: 22, tackling: 20, positioning: 86,
    transitionThreat: 92, pressResistance: 72, bigGameRating: 84,
    consistency: 80, leadership: 70, versatility: 50, weakFoot: 70,
    setPieces: 58, crossing: 36,
    height: 87, heading: 82, vision: 62, longPassing: 54, shortPassing: 60,
    ballControl: 76, agility: 84, balance: 80, reactions: 86, aggression: 78,
    interceptions: 22, marking: 20, concentration: 78, composure: 78,
    teamwork: 66, offTheBall: 86, natFitness: 82, injuryProne: 24,
    freeKick: 52, longShots: 64, volleys: 62,
    slidingTackle: 16, standingTackle: 20, jumping: 84, strength: 88,
    acceleration: 94, sprintSpeed: 92,
    traits: ["paceAbuser","physicalBeast","transitionThreat","aerialThreat"],
    playstyles: ["counterAttack","direct","vertical"],
    positions: ["ST"], face: "faces/osimhen.png", rarity: "gold"
  },
  {
    name: "Lautaro Martínez — 22/23", playerGroup: "lautaro-martinez",
    nation: "Argentina", club: "Inter Milan", position: "ST", secondaryPositions: [],
    overall: 88, attack: 89, midfield: 66, defense: 30,
    pace: 78, physical: 80, technical: 82, intelligence: 84,
    workRate: 80, creativity: 70, finishing: 88, passing: 70,
    dribbling: 80, pressing: 72, aerial: 76, stamina: 80,
    defensiveAwareness: 28, tackling: 26, positioning: 88,
    transitionThreat: 76, pressResistance: 78, bigGameRating: 86,
    consistency: 84, leadership: 76, versatility: 62, weakFoot: 78,
    setPieces: 66, crossing: 44,
    height: 76, heading: 76, vision: 72, longPassing: 62, shortPassing: 70,
    ballControl: 82, agility: 80, balance: 80, reactions: 86, aggression: 72,
    interceptions: 28, marking: 26, concentration: 84, composure: 84,
    teamwork: 78, offTheBall: 88, natFitness: 82, injuryProne: 18,
    freeKick: 60, longShots: 68, volleys: 66,
    slidingTackle: 22, standingTackle: 26, jumping: 78, strength: 80,
    acceleration: 80, sprintSpeed: 78,
    traits: ["eliteFinisher","penaltyBoxPredator","intelligentMover","bigGamePlayer"],
    playstyles: ["possession","direct","counterAttack"],
    positions: ["ST"], face: "faces/lautaro.png", rarity: "gold"
  },
];
