// ============================================================
//  FOOTBALL DRAFT — PLAYER DATABASE
//  Full attribute model for complex match engine
// ============================================================

const PLAYERS = [

  // ── GOALKEEPERS ───────────────────────────────────────────
  {
    name: "Thibaut Courtois",
    nation: "Belgium", club: "Real Madrid",
    position: "GK", secondaryPositions: [],
    overall: 91, attack: 10, midfield: 15, defense: 91,
    pace: 42, physical: 82, technical: 60, intelligence: 88,
    workRate: 68, creativity: 20, finishing: 5, passing: 70,
    dribbling: 25, pressing: 15, aerial: 88, stamina: 72,
    defensiveAwareness: 90, tackling: 20, positioning: 91,
    transitionThreat: 8, pressResistance: 75, bigGameRating: 92,
    consistency: 88, leadership: 82, versatility: 20, weakFoot: 50,
    setPieces: 30, crossing: 10,
    goalkeeperRating: 91, reflexes: 92, commandOfArea: 88, distribution: 78,
    traits: ["shotStopper", "bigGamePlayer", "aerialCommander"],
    playstyles: ["lowBlock", "organised"],
    positions: ["GK"], face: "faces/courtois.png", rarity: "gold"
  },
  {
    name: "Alisson Becker",
    nation: "Brazil", club: "Liverpool",
    position: "GK", secondaryPositions: [],
    overall: 90, attack: 8, midfield: 12, defense: 90,
    pace: 40, physical: 80, technical: 65, intelligence: 90,
    workRate: 70, creativity: 18, finishing: 5, passing: 82,
    dribbling: 22, pressing: 12, aerial: 85, stamina: 70,
    defensiveAwareness: 89, tackling: 18, positioning: 90,
    transitionThreat: 10, pressResistance: 80, bigGameRating: 90,
    consistency: 89, leadership: 85, versatility: 20, weakFoot: 55,
    setPieces: 28, crossing: 8,
    goalkeeperRating: 90, reflexes: 89, commandOfArea: 87, distribution: 88,
    traits: ["sweepingKeeper", "distributionExpert", "calmUnderPressure"],
    playstyles: ["highPress", "possession"],
    positions: ["GK"], face: "faces/alisson.png", rarity: "gold"
  },
  {
    name: "Manuel Neuer",
    nation: "Germany", club: "Bayern Munich",
    position: "GK", secondaryPositions: [],
    overall: 89, attack: 10, midfield: 14, defense: 89,
    pace: 50, physical: 82, technical: 70, intelligence: 92,
    workRate: 72, creativity: 20, finishing: 5, passing: 80,
    dribbling: 35, pressing: 18, aerial: 86, stamina: 72,
    defensiveAwareness: 90, tackling: 25, positioning: 88,
    transitionThreat: 15, pressResistance: 82, bigGameRating: 88,
    consistency: 86, leadership: 90, versatility: 35, weakFoot: 58,
    setPieces: 30, crossing: 10,
    goalkeeperRating: 89, reflexes: 87, commandOfArea: 92, distribution: 85,
    traits: ["sweepingKeeper", "leader", "aerialCommander"],
    playstyles: ["highPress", "organised"],
    positions: ["GK"], face: "faces/neuer.png", rarity: "gold"
  },
  {
    name: "Ederson",
    nation: "Brazil", club: "Man City",
    position: "GK", secondaryPositions: [],
    overall: 88, attack: 11, midfield: 15, defense: 88,
    pace: 45, physical: 80, technical: 68, intelligence: 86,
    workRate: 68, creativity: 18, finishing: 5, passing: 86,
    dribbling: 30, pressing: 14, aerial: 82, stamina: 70,
    defensiveAwareness: 87, tackling: 22, positioning: 86,
    transitionThreat: 12, pressResistance: 84, bigGameRating: 85,
    consistency: 86, leadership: 80, versatility: 25, weakFoot: 60,
    setPieces: 25, crossing: 10,
    goalkeeperRating: 88, reflexes: 86, commandOfArea: 85, distribution: 92,
    traits: ["distributionExpert", "sweepingKeeper", "calmUnderPressure"],
    playstyles: ["possession", "highPress"],
    positions: ["GK"], face: "faces/ederson.png", rarity: "gold"
  },

  // ── RIGHT BACKS ───────────────────────────────────────────
  {
    name: "Trent Alexander-Arnold",
    nation: "England", club: "Liverpool",
    position: "RB", secondaryPositions: ["CM"],
    overall: 87, attack: 80, midfield: 78, defense: 72,
    pace: 78, physical: 70, technical: 86, intelligence: 84,
    workRate: 78, creativity: 88, finishing: 58, passing: 92,
    dribbling: 75, pressing: 65, aerial: 62, stamina: 78,
    defensiveAwareness: 68, tackling: 68, positioning: 76,
    transitionThreat: 78, pressResistance: 80, bigGameRating: 84,
    consistency: 80, leadership: 70, versatility: 82, weakFoot: 70,
    setPieces: 90, crossing: 94,
    traits: ["crossingSpecialist", "setPieceExpert", "attackingFullback", "visionPasser"],
    playstyles: ["possession", "wide", "highPress"],
    positions: ["RB"], face: "faces/trent.png", rarity: "gold"
  },
  {
    name: "Achraf Hakimi",
    nation: "Morocco", club: "PSG",
    position: "RB", secondaryPositions: ["RW"],
    overall: 86, attack: 82, midfield: 72, defense: 78,
    pace: 95, physical: 76, technical: 80, intelligence: 78,
    workRate: 85, creativity: 74, finishing: 65, passing: 78,
    dribbling: 84, pressing: 72, aerial: 65, stamina: 88,
    defensiveAwareness: 74, tackling: 76, positioning: 78,
    transitionThreat: 92, pressResistance: 74, bigGameRating: 82,
    consistency: 80, leadership: 68, versatility: 80, weakFoot: 72,
    setPieces: 62, crossing: 80,
    traits: ["paceAbuser", "attackingFullback", "overlappingRunner", "transitionThreat"],
    playstyles: ["counterAttack", "wide", "direct"],
    positions: ["RB"], face: "faces/hakimi.png", rarity: "gold"
  },
  {
    name: "Dani Carvajal",
    nation: "Spain", club: "Real Madrid",
    position: "RB", secondaryPositions: [],
    overall: 85, attack: 70, midfield: 68, defense: 84,
    pace: 78, physical: 78, technical: 78, intelligence: 86,
    workRate: 86, creativity: 66, finishing: 52, passing: 78,
    dribbling: 72, pressing: 76, aerial: 70, stamina: 84,
    defensiveAwareness: 84, tackling: 82, positioning: 84,
    transitionThreat: 68, pressResistance: 78, bigGameRating: 88,
    consistency: 84, leadership: 78, versatility: 72, weakFoot: 68,
    setPieces: 58, crossing: 76,
    traits: ["bigGamePlayer", "tacticalFullback", "disciplinedDefender"],
    playstyles: ["organised", "counterAttack"],
    positions: ["RB"], face: "faces/carvajal.png", rarity: "gold"
  },
  {
    name: "Reece James",
    nation: "England", club: "Chelsea",
    position: "RB", secondaryPositions: [],
    overall: 84, attack: 74, midfield: 70, defense: 82,
    pace: 76, physical: 86, technical: 76, intelligence: 78,
    workRate: 82, creativity: 68, finishing: 56, passing: 76,
    dribbling: 74, pressing: 74, aerial: 76, stamina: 80,
    defensiveAwareness: 80, tackling: 84, positioning: 80,
    transitionThreat: 70, pressResistance: 74, bigGameRating: 80,
    consistency: 76, leadership: 72, versatility: 70, weakFoot: 66,
    setPieces: 60, crossing: 78,
    traits: ["powerfulFullback", "crossingSpecialist", "aerialThreat"],
    playstyles: ["direct", "wide"],
    positions: ["RB"], face: "faces/reecejames.png", rarity: "gold"
  },
  {
    name: "Kyle Walker",
    nation: "England", club: "Man City",
    position: "RB", secondaryPositions: [],
    overall: 83, attack: 68, midfield: 64, defense: 82,
    pace: 96, physical: 82, technical: 70, intelligence: 80,
    workRate: 84, creativity: 56, finishing: 44, passing: 70,
    dribbling: 68, pressing: 72, aerial: 70, stamina: 86,
    defensiveAwareness: 82, tackling: 78, positioning: 80,
    transitionThreat: 80, pressResistance: 72, bigGameRating: 80,
    consistency: 80, leadership: 70, versatility: 68, weakFoot: 64,
    setPieces: 44, crossing: 66,
    traits: ["elitePace", "recoveryDefender", "disciplinedDefender"],
    playstyles: ["highPress", "counterAttack"],
    positions: ["RB"], face: "faces/walker.png", rarity: "gold"
  },

  // ── LEFT BACKS ────────────────────────────────────────────
  {
    name: "Alphonso Davies",
    nation: "Canada", club: "Bayern Munich",
    position: "LB", secondaryPositions: ["LW"],
    overall: 86, attack: 79, midfield: 72, defense: 78,
    pace: 97, physical: 74, technical: 78, intelligence: 76,
    workRate: 88, creativity: 72, finishing: 58, passing: 74,
    dribbling: 84, pressing: 78, aerial: 62, stamina: 90,
    defensiveAwareness: 72, tackling: 74, positioning: 74,
    transitionThreat: 94, pressResistance: 72, bigGameRating: 80,
    consistency: 78, leadership: 65, versatility: 80, weakFoot: 72,
    setPieces: 52, crossing: 76,
    traits: ["elitePace", "attackingFullback", "transitionThreat", "overlappingRunner"],
    playstyles: ["highPress", "counterAttack", "wide"],
    positions: ["LB"], face: "faces/davies.png", rarity: "gold"
  },
  {
    name: "Andrew Robertson",
    nation: "Scotland", club: "Liverpool",
    position: "LB", secondaryPositions: [],
    overall: 85, attack: 72, midfield: 74, defense: 82,
    pace: 80, physical: 76, technical: 76, intelligence: 82,
    workRate: 94, creativity: 70, finishing: 50, passing: 80,
    dribbling: 72, pressing: 88, aerial: 68, stamina: 94,
    defensiveAwareness: 80, tackling: 80, positioning: 80,
    transitionThreat: 74, pressResistance: 76, bigGameRating: 82,
    consistency: 84, leadership: 80, versatility: 68, weakFoot: 68,
    setPieces: 56, crossing: 82,
    traits: ["highEnergyRunner", "crossingSpecialist", "pressMonster", "consistentPerformer"],
    playstyles: ["highPress", "wide"],
    positions: ["LB"], face: "faces/robertson.png", rarity: "gold"
  },
  {
    name: "Theo Hernandez",
    nation: "France", club: "AC Milan",
    position: "LB", secondaryPositions: ["LW"],
    overall: 85, attack: 80, midfield: 70, defense: 78,
    pace: 90, physical: 82, technical: 76, intelligence: 74,
    workRate: 82, creativity: 72, finishing: 62, passing: 74,
    dribbling: 80, pressing: 70, aerial: 72, stamina: 84,
    defensiveAwareness: 72, tackling: 76, positioning: 74,
    transitionThreat: 88, pressResistance: 72, bigGameRating: 80,
    consistency: 78, leadership: 68, versatility: 78, weakFoot: 70,
    setPieces: 54, crossing: 78,
    traits: ["paceAbuser", "attackingFullback", "transitionThreat"],
    playstyles: ["counterAttack", "direct", "wide"],
    positions: ["LB"], face: "faces/theohernandez.png", rarity: "gold"
  },
  {
    name: "Grimaldo",
    nation: "Spain", club: "Bayer Leverkusen",
    position: "LB", secondaryPositions: [],
    overall: 83, attack: 76, midfield: 72, defense: 78,
    pace: 82, physical: 70, technical: 80, intelligence: 80,
    workRate: 86, creativity: 74, finishing: 58, passing: 80,
    dribbling: 76, pressing: 78, aerial: 60, stamina: 86,
    defensiveAwareness: 76, tackling: 74, positioning: 78,
    transitionThreat: 76, pressResistance: 78, bigGameRating: 76,
    consistency: 80, leadership: 68, versatility: 72, weakFoot: 68,
    setPieces: 60, crossing: 80,
    traits: ["attackingFullback", "crossingSpecialist", "technicalFullback"],
    playstyles: ["possession", "wide"],
    positions: ["LB"], face: "faces/grimaldo.png", rarity: "gold"
  },

  // ── CENTRE BACKS ──────────────────────────────────────────
  {
    name: "Virgil van Dijk",
    nation: "Netherlands", club: "Liverpool",
    position: "CB", secondaryPositions: [],
    overall: 90, attack: 40, midfield: 52, defense: 90,
    pace: 76, physical: 90, technical: 72, intelligence: 90,
    workRate: 74, creativity: 44, finishing: 48, passing: 82,
    dribbling: 54, pressing: 68, aerial: 94, stamina: 78,
    defensiveAwareness: 90, tackling: 88, positioning: 90,
    transitionThreat: 38, pressResistance: 84, bigGameRating: 90,
    consistency: 88, leadership: 92, versatility: 44, weakFoot: 76,
    setPieces: 72, crossing: 44,
    traits: ["aerialDominator", "leader", "organiser", "setPieceThreat"],
    playstyles: ["highPress", "organised", "possession"],
    positions: ["CB"], face: "faces/vandijk.png", rarity: "gold"
  },
  {
    name: "Rúben Dias",
    nation: "Portugal", club: "Man City",
    position: "CB", secondaryPositions: [],
    overall: 89, attack: 35, midfield: 50, defense: 89,
    pace: 74, physical: 86, technical: 74, intelligence: 92,
    workRate: 78, creativity: 40, finishing: 38, passing: 80,
    dribbling: 50, pressing: 70, aerial: 86, stamina: 78,
    defensiveAwareness: 92, tackling: 86, positioning: 90,
    transitionThreat: 30, pressResistance: 82, bigGameRating: 88,
    consistency: 90, leadership: 88, versatility: 42, weakFoot: 74,
    setPieces: 66, crossing: 38,
    traits: ["organisedDefender", "leader", "intelligentPositioner", "consistentPerformer"],
    playstyles: ["organised", "possession", "highPress"],
    positions: ["CB"], face: "faces/rubendias.png", rarity: "gold"
  },
  {
    name: "William Saliba",
    nation: "France", club: "Arsenal",
    position: "CB", secondaryPositions: [],
    overall: 87, attack: 32, midfield: 46, defense: 87,
    pace: 82, physical: 84, technical: 72, intelligence: 84,
    workRate: 76, creativity: 36, finishing: 32, passing: 78,
    dribbling: 52, pressing: 68, aerial: 82, stamina: 78,
    defensiveAwareness: 86, tackling: 86, positioning: 86,
    transitionThreat: 34, pressResistance: 78, bigGameRating: 84,
    consistency: 84, leadership: 74, versatility: 42, weakFoot: 72,
    setPieces: 60, crossing: 34,
    traits: ["recoveryDefender", "modernCentreback", "aerialDominator"],
    playstyles: ["highPress", "organised"],
    positions: ["CB"], face: "faces/saliba.png", rarity: "gold"
  },
  {
    name: "Antonio Rüdiger",
    nation: "Germany", club: "Real Madrid",
    position: "CB", secondaryPositions: [],
    overall: 87, attack: 38, midfield: 48, defense: 87,
    pace: 84, physical: 92, technical: 66, intelligence: 82,
    workRate: 80, creativity: 36, finishing: 40, passing: 72,
    dribbling: 50, pressing: 72, aerial: 86, stamina: 82,
    defensiveAwareness: 84, tackling: 88, positioning: 82,
    transitionThreat: 44, pressResistance: 76, bigGameRating: 86,
    consistency: 82, leadership: 80, versatility: 46, weakFoot: 70,
    setPieces: 58, crossing: 36,
    traits: ["physicalBeast", "aerialDominator", "aggressiveDefender", "bigGamePlayer"],
    playstyles: ["highPress", "direct"],
    positions: ["CB"], face: "faces/rudiger.png", rarity: "gold"
  },
  {
    name: "Alessandro Bastoni",
    nation: "Italy", club: "Inter Milan",
    position: "CB", secondaryPositions: ["LB"],
    overall: 86, attack: 42, midfield: 60, defense: 84,
    pace: 74, physical: 80, technical: 82, intelligence: 86,
    workRate: 76, creativity: 62, finishing: 38, passing: 84,
    dribbling: 66, pressing: 68, aerial: 78, stamina: 76,
    defensiveAwareness: 84, tackling: 80, positioning: 84,
    transitionThreat: 52, pressResistance: 84, bigGameRating: 82,
    consistency: 82, leadership: 74, versatility: 72, weakFoot: 78,
    setPieces: 58, crossing: 48,
    traits: ["ballPlayingDefender", "modernCentreback", "intelligentPositioner"],
    playstyles: ["possession", "organised"],
    positions: ["CB"], face: "faces/bastoni.png", rarity: "gold"
  },
  {
    name: "Marquinhos",
    nation: "Brazil", club: "PSG",
    position: "CB", secondaryPositions: ["CDM"],
    overall: 87, attack: 36, midfield: 55, defense: 87,
    pace: 78, physical: 80, technical: 76, intelligence: 90,
    workRate: 80, creativity: 46, finishing: 36, passing: 80,
    dribbling: 56, pressing: 74, aerial: 82, stamina: 80,
    defensiveAwareness: 90, tackling: 84, positioning: 88,
    transitionThreat: 36, pressResistance: 80, bigGameRating: 86,
    consistency: 84, leadership: 86, versatility: 74, weakFoot: 76,
    setPieces: 62, crossing: 38,
    traits: ["intelligentPositioner", "leader", "versatileDefender"],
    playstyles: ["organised", "possession"],
    positions: ["CB"], face: "faces/marquinhos.png", rarity: "gold"
  },

  // ── CDM ───────────────────────────────────────────────────
  {
    name: "Rodri",
    nation: "Spain", club: "Man City",
    position: "CDM", secondaryPositions: ["CM"],
    overall: 91, attack: 62, midfield: 91, defense: 86,
    pace: 68, physical: 84, technical: 86, intelligence: 95,
    workRate: 88, creativity: 78, finishing: 60, passing: 90,
    dribbling: 72, pressing: 84, aerial: 80, stamina: 86,
    defensiveAwareness: 90, tackling: 86, positioning: 92,
    transitionThreat: 58, pressResistance: 92, bigGameRating: 90,
    consistency: 92, leadership: 86, versatility: 80, weakFoot: 80,
    setPieces: 70, crossing: 62,
    traits: ["midfielderColossus", "calmUnderPressure", "intelligentPositioner", "consistentPerformer"],
    playstyles: ["possession", "organised", "highPress"],
    positions: ["CDM"], face: "faces/rodri.png", rarity: "special"
  },
  {
    name: "Casemiro",
    nation: "Brazil", club: "Man United",
    position: "CDM", secondaryPositions: [],
    overall: 86, attack: 55, midfield: 84, defense: 84,
    pace: 62, physical: 88, technical: 74, intelligence: 86,
    workRate: 86, creativity: 62, finishing: 58, passing: 76,
    dribbling: 64, pressing: 82, aerial: 84, stamina: 84,
    defensiveAwareness: 88, tackling: 90, positioning: 86,
    transitionThreat: 50, pressResistance: 82, bigGameRating: 86,
    consistency: 82, leadership: 82, versatility: 68, weakFoot: 76,
    setPieces: 62, crossing: 52,
    traits: ["hardTackler", "aerialDominator", "protectiveScreener", "bigGamePlayer"],
    playstyles: ["organised", "direct", "highPress"],
    positions: ["CDM"], face: "faces/casemiro.png", rarity: "gold"
  },
  {
    name: "Declan Rice",
    nation: "England", club: "Arsenal",
    position: "CDM", secondaryPositions: ["CM"],
    overall: 86, attack: 64, midfield: 85, defense: 82,
    pace: 72, physical: 84, technical: 78, intelligence: 84,
    workRate: 92, creativity: 66, finishing: 56, passing: 80,
    dribbling: 70, pressing: 88, aerial: 78, stamina: 90,
    defensiveAwareness: 84, tackling: 84, positioning: 84,
    transitionThreat: 62, pressResistance: 80, bigGameRating: 82,
    consistency: 84, leadership: 80, versatility: 74, weakFoot: 74,
    setPieces: 60, crossing: 58,
    traits: ["pressMonster", "boxToBox", "energeticRunner", "disciplinedDefender"],
    playstyles: ["highPress", "organised"],
    positions: ["CDM"], face: "faces/declanrice.png", rarity: "gold"
  },
  {
    name: "Aurélien Tchouaméni",
    nation: "France", club: "Real Madrid",
    position: "CDM", secondaryPositions: ["CM"],
    overall: 85, attack: 58, midfield: 83, defense: 82,
    pace: 70, physical: 86, technical: 78, intelligence: 84,
    workRate: 84, creativity: 64, finishing: 52, passing: 78,
    dribbling: 68, pressing: 80, aerial: 80, stamina: 84,
    defensiveAwareness: 84, tackling: 84, positioning: 84,
    transitionThreat: 56, pressResistance: 80, bigGameRating: 80,
    consistency: 82, leadership: 74, versatility: 72, weakFoot: 76,
    setPieces: 58, crossing: 52,
    traits: ["athleticMidfielder", "aerialDominator", "disciplinedDefender"],
    playstyles: ["organised", "counterAttack"],
    positions: ["CDM"], face: "faces/tchouameni.png", rarity: "gold"
  },

  // ── CM ────────────────────────────────────────────────────
  {
    name: "Jude Bellingham",
    nation: "England", club: "Real Madrid",
    position: "CM", secondaryPositions: ["CAM"],
    overall: 91, attack: 88, midfield: 89, defense: 70,
    pace: 80, physical: 84, technical: 88, intelligence: 90,
    workRate: 88, creativity: 86, finishing: 84, passing: 86,
    dribbling: 86, pressing: 80, aerial: 80, stamina: 88,
    defensiveAwareness: 68, tackling: 70, positioning: 88,
    transitionThreat: 84, pressResistance: 86, bigGameRating: 94,
    consistency: 88, leadership: 88, versatility: 86, weakFoot: 80,
    setPieces: 72, crossing: 72,
    traits: ["bigGamePlayer", "boxToBox", "goalScoringMidfielder", "leader"],
    playstyles: ["direct", "counterAttack", "possession"],
    positions: ["CM"], face: "faces/bellingham.png", rarity: "special"
  },
  {
    name: "Kevin De Bruyne",
    nation: "Belgium", club: "Man City",
    position: "CM", secondaryPositions: ["CAM"],
    overall: 91, attack: 86, midfield: 91, defense: 64,
    pace: 74, physical: 76, technical: 92, intelligence: 94,
    workRate: 80, creativity: 96, finishing: 80, passing: 96,
    dribbling: 84, pressing: 68, aerial: 68, stamina: 80,
    defensiveAwareness: 58, tackling: 58, positioning: 86,
    transitionThreat: 80, pressResistance: 86, bigGameRating: 90,
    consistency: 86, leadership: 82, versatility: 80, weakFoot: 82,
    setPieces: 88, crossing: 90,
    traits: ["visionPasser", "chanceCreator", "setPieceExpert", "crossingSpecialist"],
    playstyles: ["possession", "wide", "counterAttack"],
    positions: ["CM"], face: "faces/debruyne.png", rarity: "special"
  },
  {
    name: "Luka Modric",
    nation: "Croatia", club: "Real Madrid",
    position: "CM", secondaryPositions: [],
    overall: 88, attack: 74, midfield: 89, defense: 72,
    pace: 68, physical: 66, technical: 92, intelligence: 94,
    workRate: 86, creativity: 88, finishing: 66, passing: 92,
    dribbling: 88, pressing: 78, aerial: 58, stamina: 84,
    defensiveAwareness: 70, tackling: 70, positioning: 84,
    transitionThreat: 68, pressResistance: 92, bigGameRating: 92,
    consistency: 86, leadership: 84, versatility: 76, weakFoot: 86,
    setPieces: 74, crossing: 68,
    traits: ["technicalMaestro", "calmUnderPressure", "bigGamePlayer", "visionPasser"],
    playstyles: ["possession", "organised"],
    positions: ["CM"], face: "faces/modric.png", rarity: "gold"
  },
  {
    name: "Toni Kroos",
    nation: "Germany", club: "Real Madrid",
    position: "CM", secondaryPositions: [],
    overall: 88, attack: 72, midfield: 90, defense: 70,
    pace: 58, physical: 68, technical: 92, intelligence: 96,
    workRate: 78, creativity: 86, finishing: 62, passing: 96,
    dribbling: 76, pressing: 64, aerial: 60, stamina: 76,
    defensiveAwareness: 68, tackling: 62, positioning: 82,
    transitionThreat: 60, pressResistance: 90, bigGameRating: 90,
    consistency: 88, leadership: 82, versatility: 70, weakFoot: 88,
    setPieces: 86, crossing: 80,
    traits: ["elitePasser", "setPieceExpert", "metronomeMidfielder", "calmUnderPressure"],
    playstyles: ["possession", "organised"],
    positions: ["CM"], face: "faces/kroos.png", rarity: "gold"
  },
  {
    name: "Martin Ødegaard",
    nation: "Norway", club: "Arsenal",
    position: "CM", secondaryPositions: ["CAM"],
    overall: 88, attack: 82, midfield: 88, defense: 60,
    pace: 74, physical: 66, technical: 90, intelligence: 88,
    workRate: 80, creativity: 90, finishing: 74, passing: 88,
    dribbling: 86, pressing: 74, aerial: 56, stamina: 78,
    defensiveAwareness: 58, tackling: 58, positioning: 82,
    transitionThreat: 72, pressResistance: 84, bigGameRating: 84,
    consistency: 84, leadership: 84, versatility: 78, weakFoot: 80,
    setPieces: 78, crossing: 70,
    traits: ["chanceCreator", "technicalMaestro", "leader", "visionPasser"],
    playstyles: ["possession", "highPress"],
    positions: ["CM"], face: "faces/odegaard.png", rarity: "gold"
  },
  {
    name: "Pedri",
    nation: "Spain", club: "Barcelona",
    position: "CM", secondaryPositions: ["CAM"],
    overall: 88, attack: 78, midfield: 88, defense: 62,
    pace: 72, physical: 62, technical: 92, intelligence: 90,
    workRate: 82, creativity: 88, finishing: 66, passing: 88,
    dribbling: 90, pressing: 78, aerial: 52, stamina: 80,
    defensiveAwareness: 60, tackling: 60, positioning: 82,
    transitionThreat: 68, pressResistance: 90, bigGameRating: 82,
    consistency: 82, leadership: 72, versatility: 76, weakFoot: 82,
    setPieces: 68, crossing: 64,
    traits: ["technicalMaestro", "calmUnderPressure", "dribbleMaestro", "pressResistant"],
    playstyles: ["possession", "highPress"],
    positions: ["CM"], face: "faces/pedri.png", rarity: "gold"
  },
  {
    name: "Gavi",
    nation: "Spain", club: "Barcelona",
    position: "CM", secondaryPositions: [],
    overall: 87, attack: 76, midfield: 87, defense: 64,
    pace: 74, physical: 66, technical: 88, intelligence: 84,
    workRate: 92, creativity: 82, finishing: 60, passing: 84,
    dribbling: 86, pressing: 90, aerial: 52, stamina: 90,
    defensiveAwareness: 62, tackling: 66, positioning: 78,
    transitionThreat: 66, pressResistance: 86, bigGameRating: 80,
    consistency: 80, leadership: 74, versatility: 72, weakFoot: 80,
    setPieces: 62, crossing: 60,
    traits: ["pressMonster", "energeticRunner", "technicalMaestro", "highWorkRate"],
    playstyles: ["highPress", "possession"],
    positions: ["CM"], face: "faces/gavi.png", rarity: "gold"
  },

  // ── CAM ───────────────────────────────────────────────────
  {
    name: "Bruno Fernandes",
    nation: "Portugal", club: "Man United",
    position: "CAM", secondaryPositions: ["CM"],
    overall: 87, attack: 84, midfield: 86, defense: 58,
    pace: 72, physical: 70, technical: 86, intelligence: 84,
    workRate: 82, creativity: 88, finishing: 80, passing: 86,
    dribbling: 78, pressing: 72, aerial: 68, stamina: 80,
    defensiveAwareness: 54, tackling: 54, positioning: 82,
    transitionThreat: 74, pressResistance: 80, bigGameRating: 82,
    consistency: 74, leadership: 82, versatility: 76, weakFoot: 76,
    setPieces: 84, crossing: 72,
    traits: ["chanceCreator", "setPieceExpert", "goalScoringMidfielder", "leader"],
    playstyles: ["direct", "possession"],
    positions: ["CAM"], face: "faces/brunofernandes.png", rarity: "gold"
  },
  {
    name: "Bernardo Silva",
    nation: "Portugal", club: "Man City",
    position: "CAM", secondaryPositions: ["CM", "RW"],
    overall: 87, attack: 82, midfield: 86, defense: 65,
    pace: 74, physical: 68, technical: 90, intelligence: 88,
    workRate: 92, creativity: 84, finishing: 72, passing: 86,
    dribbling: 86, pressing: 84, aerial: 60, stamina: 90,
    defensiveAwareness: 62, tackling: 62, positioning: 80,
    transitionThreat: 72, pressResistance: 88, bigGameRating: 84,
    consistency: 86, leadership: 72, versatility: 90, weakFoot: 82,
    setPieces: 66, crossing: 68,
    traits: ["technicalMaestro", "highWorkRate", "pressMonster", "versatilePlayer"],
    playstyles: ["possession", "highPress"],
    positions: ["CAM"], face: "faces/bernardo.png", rarity: "gold"
  },
  {
    name: "Florian Wirtz",
    nation: "Germany", club: "Bayer Leverkusen",
    position: "CAM", secondaryPositions: ["RW"],
    overall: 89, attack: 88, midfield: 86, defense: 42,
    pace: 78, physical: 66, technical: 92, intelligence: 88,
    workRate: 76, creativity: 92, finishing: 82, passing: 86,
    dribbling: 90, pressing: 68, aerial: 54, stamina: 76,
    defensiveAwareness: 40, tackling: 40, positioning: 84,
    transitionThreat: 80, pressResistance: 86, bigGameRating: 86,
    consistency: 82, leadership: 68, versatility: 78, weakFoot: 82,
    setPieces: 72, crossing: 70,
    traits: ["chanceCreator", "technicalMaestro", "dribbleMaestro", "creativeThreat"],
    playstyles: ["possession", "direct", "counterAttack"],
    positions: ["CAM"], face: "faces/wirtz.png", rarity: "special"
  },
  {
    name: "Phil Foden",
    nation: "England", club: "Man City",
    position: "CAM", secondaryPositions: ["LW", "RW"],
    overall: 90, attack: 89, midfield: 84, defense: 44,
    pace: 80, physical: 68, technical: 92, intelligence: 88,
    workRate: 78, creativity: 90, finishing: 84, passing: 84,
    dribbling: 90, pressing: 72, aerial: 60, stamina: 78,
    defensiveAwareness: 42, tackling: 42, positioning: 86,
    transitionThreat: 80, pressResistance: 86, bigGameRating: 86,
    consistency: 84, leadership: 68, versatility: 82, weakFoot: 80,
    setPieces: 68, crossing: 72,
    traits: ["technicalMaestro", "insideForward", "dribbleMaestro", "creativeThreat"],
    playstyles: ["possession", "direct"],
    positions: ["CAM"], face: "faces/foden.png", rarity: "gold"
  },

  // ── LEFT WING ─────────────────────────────────────────────
  {
    name: "Vinicius Jr",
    nation: "Brazil", club: "Real Madrid",
    position: "LW", secondaryPositions: [],
    overall: 92, attack: 92, midfield: 74, defense: 34,
    pace: 97, physical: 74, technical: 88, intelligence: 80,
    workRate: 72, creativity: 88, finishing: 84, passing: 74,
    dribbling: 96, pressing: 62, aerial: 64, stamina: 80,
    defensiveAwareness: 32, tackling: 28, positioning: 82,
    transitionThreat: 96, pressResistance: 80, bigGameRating: 90,
    consistency: 80, leadership: 66, versatility: 66, weakFoot: 74,
    setPieces: 54, crossing: 72,
    traits: ["elitePace", "dribbleMaestro", "insideForward", "paceAbuser", "transitionThreat"],
    playstyles: ["counterAttack", "direct", "wide"],
    positions: ["LW"], face: "faces/vinicius.png", rarity: "special"
  },
  {
    name: "Kylian Mbappé",
    nation: "France", club: "Real Madrid",
    position: "LW", secondaryPositions: ["ST"],
    overall: 95, attack: 95, midfield: 78, defense: 36,
    pace: 98, physical: 80, technical: 90, intelligence: 88,
    workRate: 74, creativity: 86, finishing: 94, passing: 82,
    dribbling: 92, pressing: 66, aerial: 76, stamina: 84,
    defensiveAwareness: 35, tackling: 28, positioning: 94,
    transitionThreat: 98, pressResistance: 88, bigGameRating: 96,
    consistency: 90, leadership: 80, versatility: 82, weakFoot: 86,
    setPieces: 70, crossing: 78,
    traits: ["eliteFinisher", "elitePace", "transitionThreat", "paceAbuser", "bigGamePlayer", "insideForward"],
    playstyles: ["counterAttack", "direct", "vertical"],
    positions: ["LW"], face: "faces/mbappe.png", rarity: "special"
  },
  {
    name: "Bukayo Saka",
    nation: "England", club: "Arsenal",
    position: "LW", secondaryPositions: ["RW"],
    overall: 89, attack: 89, midfield: 78, defense: 56,
    pace: 84, physical: 72, technical: 86, intelligence: 84,
    workRate: 88, creativity: 84, finishing: 78, passing: 82,
    dribbling: 88, pressing: 82, aerial: 64, stamina: 88,
    defensiveAwareness: 52, tackling: 54, positioning: 82,
    transitionThreat: 82, pressResistance: 82, bigGameRating: 86,
    consistency: 88, leadership: 74, versatility: 84, weakFoot: 80,
    setPieces: 70, crossing: 80,
    traits: ["consistentPerformer", "dribbleMaestro", "insideForward", "highWorkRate"],
    playstyles: ["highPress", "wide", "possession"],
    positions: ["LW"], face: "faces/saka.png", rarity: "gold"
  },
  {
    name: "Rafael Leão",
    nation: "Portugal", club: "AC Milan",
    position: "LW", secondaryPositions: ["ST"],
    overall: 86, attack: 88, midfield: 66, defense: 30,
    pace: 94, physical: 76, technical: 82, intelligence: 74,
    workRate: 64, creativity: 80, finishing: 80, passing: 72,
    dribbling: 90, pressing: 52, aerial: 70, stamina: 74,
    defensiveAwareness: 28, tackling: 26, positioning: 78,
    transitionThreat: 92, pressResistance: 76, bigGameRating: 78,
    consistency: 74, leadership: 60, versatility: 70, weakFoot: 74,
    setPieces: 52, crossing: 70,
    traits: ["elitePace", "dribbleMaestro", "transitionThreat", "paceAbuser"],
    playstyles: ["counterAttack", "direct", "wide"],
    positions: ["LW"], face: "faces/leao.png", rarity: "gold"
  },

  // ── RIGHT WING ────────────────────────────────────────────
  {
    name: "Mohamed Salah",
    nation: "Egypt", club: "Liverpool",
    position: "RW", secondaryPositions: ["ST"],
    overall: 91, attack: 91, midfield: 72, defense: 44,
    pace: 90, physical: 74, technical: 86, intelligence: 86,
    workRate: 82, creativity: 80, finishing: 90, passing: 76,
    dribbling: 88, pressing: 70, aerial: 62, stamina: 86,
    defensiveAwareness: 42, tackling: 40, positioning: 88,
    transitionThreat: 88, pressResistance: 82, bigGameRating: 88,
    consistency: 90, leadership: 72, versatility: 74, weakFoot: 80,
    setPieces: 66, crossing: 68,
    traits: ["eliteFinisher", "insideForward", "consistentPerformer", "paceAbuser"],
    playstyles: ["counterAttack", "direct", "wide"],
    positions: ["RW"], face: "faces/salah.png", rarity: "gold"
  },
  {
    name: "Rodrygo",
    nation: "Brazil", club: "Real Madrid",
    position: "RW", secondaryPositions: ["LW"],
    overall: 85, attack: 85, midfield: 72, defense: 36,
    pace: 86, physical: 66, technical: 84, intelligence: 80,
    workRate: 76, creativity: 80, finishing: 78, passing: 76,
    dribbling: 86, pressing: 64, aerial: 60, stamina: 78,
    defensiveAwareness: 34, tackling: 32, positioning: 78,
    transitionThreat: 82, pressResistance: 76, bigGameRating: 86,
    consistency: 78, leadership: 64, versatility: 74, weakFoot: 78,
    setPieces: 58, crossing: 68,
    traits: ["bigGamePlayer", "dribbleMaestro", "insideForward", "clevreMovement"],
    playstyles: ["counterAttack", "direct"],
    positions: ["RW"], face: "faces/rodrygo.png", rarity: "gold"
  },
  {
    name: "Ousmane Dembélé",
    nation: "France", club: "PSG",
    position: "RW", secondaryPositions: ["LW"],
    overall: 86, attack: 87, midfield: 68, defense: 32,
    pace: 92, physical: 68, technical: 88, intelligence: 74,
    workRate: 70, creativity: 84, finishing: 76, passing: 74,
    dribbling: 92, pressing: 60, aerial: 58, stamina: 74,
    defensiveAwareness: 30, tackling: 28, positioning: 74,
    transitionThreat: 90, pressResistance: 74, bigGameRating: 76,
    consistency: 70, leadership: 56, versatility: 72, weakFoot: 80,
    setPieces: 54, crossing: 72,
    traits: ["dribbleMaestro", "elitePace", "unpredictable", "transitionThreat"],
    playstyles: ["counterAttack", "direct", "wide"],
    positions: ["RW"], face: "faces/dembele.png", rarity: "gold"
  },

  // ── STRIKERS ──────────────────────────────────────────────
  {
    name: "Erling Haaland",
    nation: "Norway", club: "Man City",
    position: "ST", secondaryPositions: [],
    overall: 94, attack: 95, midfield: 58, defense: 22,
    pace: 88, physical: 92, technical: 76, intelligence: 82,
    workRate: 68, creativity: 62, finishing: 98, passing: 62,
    dribbling: 74, pressing: 58, aerial: 90, stamina: 82,
    defensiveAwareness: 22, tackling: 18, positioning: 96,
    transitionThreat: 90, pressResistance: 78, bigGameRating: 90,
    consistency: 86, leadership: 74, versatility: 42, weakFoot: 74,
    setPieces: 68, crossing: 42,
    traits: ["eliteFinisher", "aerialDominator", "penaltyBoxPredator", "physicalBeast", "paceAbuser"],
    playstyles: ["direct", "counterAttack", "vertical"],
    positions: ["ST"], face: "faces/haaland.png", rarity: "special"
  },
  {
    name: "Harry Kane",
    nation: "England", club: "Bayern Munich",
    position: "ST", secondaryPositions: [],
    overall: 91, attack: 92, midfield: 72, defense: 28,
    pace: 70, physical: 82, technical: 84, intelligence: 92,
    workRate: 80, creativity: 78, finishing: 92, passing: 84,
    dribbling: 72, pressing: 68, aerial: 88, stamina: 80,
    defensiveAwareness: 26, tackling: 24, positioning: 94,
    transitionThreat: 68, pressResistance: 84, bigGameRating: 90,
    consistency: 88, leadership: 86, versatility: 68, weakFoot: 84,
    setPieces: 82, crossing: 54,
    traits: ["eliteFinisher", "setPieceThreat", "linkUpPlay", "intelligentMover", "leader"],
    playstyles: ["possession", "direct", "wide"],
    positions: ["ST"], face: "faces/kane.png", rarity: "gold"
  },
  {
    name: "Robert Lewandowski",
    nation: "Poland", club: "Barcelona",
    position: "ST", secondaryPositions: [],
    overall: 90, attack: 91, midfield: 68, defense: 26,
    pace: 74, physical: 82, technical: 84, intelligence: 90,
    workRate: 76, creativity: 72, finishing: 94, passing: 76,
    dribbling: 74, pressing: 66, aerial: 84, stamina: 78,
    defensiveAwareness: 24, tackling: 22, positioning: 96,
    transitionThreat: 66, pressResistance: 82, bigGameRating: 88,
    consistency: 88, leadership: 80, versatility: 62, weakFoot: 82,
    setPieces: 74, crossing: 44,
    traits: ["eliteFinisher", "penaltyBoxPredator", "intelligentMover", "setPieceThreat"],
    playstyles: ["possession", "direct"],
    positions: ["ST"], face: "faces/lewandowski.png", rarity: "gold"
  },
  {
    name: "Victor Osimhen",
    nation: "Nigeria", club: "Galatasaray",
    position: "ST", secondaryPositions: [],
    overall: 88, attack: 89, midfield: 60, defense: 24,
    pace: 92, physical: 88, technical: 74, intelligence: 76,
    workRate: 72, creativity: 62, finishing: 86, passing: 60,
    dribbling: 74, pressing: 64, aerial: 80, stamina: 80,
    defensiveAwareness: 22, tackling: 20, positioning: 84,
    transitionThreat: 90, pressResistance: 72, bigGameRating: 82,
    consistency: 78, leadership: 70, versatility: 50, weakFoot: 70,
    setPieces: 58, crossing: 36,
    traits: ["paceAbuser", "physicalBeast", "transitionThreat", "aerialThreat"],
    playstyles: ["counterAttack", "direct", "vertical"],
    positions: ["ST"], face: "faces/osimhen.png", rarity: "gold"
  },
  {
    name: "Lautaro Martínez",
    nation: "Argentina", club: "Inter Milan",
    position: "ST", secondaryPositions: [],
    overall: 88, attack: 89, midfield: 66, defense: 30,
    pace: 78, physical: 80, technical: 82, intelligence: 84,
    workRate: 80, creativity: 70, finishing: 88, passing: 70,
    dribbling: 80, pressing: 72, aerial: 76, stamina: 80,
    defensiveAwareness: 28, tackling: 26, positioning: 88,
    transitionThreat: 76, pressResistance: 78, bigGameRating: 86,
    consistency: 84, leadership: 76, versatility: 62, weakFoot: 78,
    setPieces: 66, crossing: 44,
    traits: ["eliteFinisher", "penaltyBoxPredator", "intelligentMover", "bigGamePlayer"],
    playstyles: ["possession", "direct", "counterAttack"],
    positions: ["ST"], face: "faces/lautaro.png", rarity: "gold"
  },
  {
    name: "Darwin Núñez",
    nation: "Uruguay", club: "Liverpool",
    position: "ST", secondaryPositions: ["LW"],
    overall: 84, attack: 85, midfield: 58, defense: 25,
    pace: 92, physical: 84, technical: 70, intelligence: 68,
    workRate: 76, creativity: 60, finishing: 78, passing: 60,
    dribbling: 74, pressing: 68, aerial: 80, stamina: 82,
    defensiveAwareness: 24, tackling: 22, positioning: 74,
    transitionThreat: 90, pressResistance: 64, bigGameRating: 74,
    consistency: 64, leadership: 60, versatility: 60, weakFoot: 72,
    setPieces: 56, crossing: 36,
    traits: ["paceAbuser", "physicalBeast", "transitionThreat", "aerialThreat"],
    playstyles: ["counterAttack", "direct", "vertical"],
    positions: ["ST"], face: "faces/nunez.png", rarity: "gold"
  }
];
